"""
Structure Pipeline — door library, catalog, and deterministic selection.

A building needs the RIGHT door for each situation: a plain bedroom door, a panelled interior
door, an iron-banded cellar door, a wide double door, a grand main entrance, a courtyard gate.
This module:
  * generates a LIBRARY of detailed multi-resolution door leaves (thin, hinge stile at local X=0,
    knob on the latch side — the convention DoorManager pivots on),
  * holds the DOOR_CATALOG (each door's real size + traits), shared by the realizer AND the checks,
  * selects a door deterministically from the opening width + room purpose + lockable + exterior.

Free-swinging (physics) doors and left/right hinge MIRRORING are tracked in docs/StructurePipelineGaps.md
(the engine + mirrored templates are follow-ups); this module records the intended `swing` per door.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

from .detail import DetailCanvas, AIR

_REPO = Path(__file__).resolve().parents[2]
TEMPLATES_DIR = _REPO / "resources" / "templates"

FRAME = "Log"      # dark stiles/rails/bands
PANEL = "Wood"     # plank / panel fill
IRON = "Metal"     # bands, studs
KNOB = "Gold"      # knob / ring


@dataclass(frozen=True)
class DoorDef:
    name: str
    width: int          # opening width it fills (cubes)
    height: int         # opening height it needs (cubes)
    style: str          # plank | panel | iron | double | grand | gate
    lockable: bool      # carries a lock/keyhole (visually + semantically appropriate)
    swing: str          # "kinematic" (engine open/close) | "free" (physics free-swing — engine TODO)
    contexts: tuple     # situations this door suits


# The catalog. door_wood / door_wood_wide come from gen_door.py (panel + double); the rest are
# generated by this module. Names are the actual .voxel template names so the realizer can place them.
DOOR_CATALOG: Dict[str, DoorDef] = {
    "door_plank":      DoorDef("door_plank",      1, 2, "plank",  False, "kinematic", ("bedroom", "interior", "closet", "servant")),
    "door_wood":       DoorDef("door_wood",       1, 2, "panel",  True,  "kinematic", ("interior", "bedroom", "study", "hall")),
    "door_iron":       DoorDef("door_iron",       1, 2, "iron",   True,  "kinematic", ("cellar", "vault", "storeroom", "prison", "lockable")),
    "door_wood_wide":  DoorDef("door_wood_wide",  2, 2, "double", True,  "kinematic", ("hall", "exterior", "main")),
    "door_grand":      DoorDef("door_grand",      2, 3, "grand",  True,  "free",      ("entrance", "main", "exterior", "manor", "temple")),
    "gate_timber":     DoorDef("gate_timber",     3, 3, "gate",   True,  "free",      ("gate", "courtyard", "barn", "wall", "keep")),
}

# Generated here (door_wood / door_wood_wide come from gen_door.py)
_GENERATED = ("door_plank", "door_iron", "door_grand", "gate_timber")


# --------------------------------------------------------------------------- leaf builders (micro)

def _knob(c: DetailCanvas, W: int, mid_y: int, depth: int) -> None:
    """A knob/ring on the latch side (away from the hinge at X=0), both faces."""
    for z in (0, depth - 1):
        c.set_micro_cell(W - 2, mid_y, z, KNOB)
        c.set_micro_cell(W - 2, mid_y + 1, z, KNOB)


def build_plank(w=1, h=2, depth=3) -> DetailCanvas:
    """Humble vertical-plank door: solid planks + two ledge braces + a small knob."""
    c = DetailCanvas()
    W, H = w * 9, h * 9
    c.fill_micro_box(0, 0, 0, W, H, depth, PANEL)
    # vertical plank grooves on the front face (carve 1-micro reveals every 3 micro)
    for gx in range(3, W, 3):
        for y in range(H):
            c.set_micro_cell(gx, y, depth - 1, AIR)
    for ly in (int(H * 0.25), int(H * 0.7)):           # two horizontal ledge braces
        c.fill_micro_box(0, ly, depth - 1, W, 2, 1, FRAME)
    _knob(c, W, H // 2, depth)
    return c


def build_iron(w=1, h=2, depth=3) -> DetailCanvas:
    """Iron-banded door: wood leaf, three metal bands with studs, a ring handle."""
    c = DetailCanvas()
    W, H = w * 9, h * 9
    c.fill_micro_box(0, 0, 0, W, H, depth, PANEL)
    for by in (int(H * 0.15), int(H * 0.5), int(H * 0.85)):    # bands
        c.fill_micro_box(0, by, depth - 1, W, 2, 1, IRON)
        for sx in range(1, W, 3):                              # studs on the band
            c.set_micro_cell(sx, by, depth - 1, IRON)
    for z in (0, depth - 1):                                   # ring handle (latch side)
        c.set_micro_cell(W - 2, H // 2, z, KNOB)
        c.set_micro_cell(W - 3, H // 2, z, KNOB)
    return c


def build_panelled(w, h, depth=3, frame=2, grand=False) -> DetailCanvas:
    """Framed door with recessed panels (panel/double/grand). Heavier frame + extra rails if grand."""
    c = DetailCanvas()
    W, H = w * 9, h * 9
    c.fill_micro_box(0, 0, 0, W, H, depth, PANEL)
    # frame: stiles (left/right) + rails (top/bottom) + mid rail(s) in FRAME material on the front
    def band(x, y, bw, bh):
        c.fill_micro_box(x, y, depth - 1, bw, bh, 1, FRAME)
    band(0, 0, frame, H); band(W - frame, 0, frame, H)        # stiles
    band(0, 0, W, frame); band(0, H - frame, W, frame)        # top/bottom rails
    rails = [H // 2] + ([H // 3, 2 * H // 3] if grand else [])
    for ry in rails:
        band(0, ry, W, frame)
    if w > 1:                                                 # center mullion for multi-leaf
        band(W // 2 - 1, 0, 2, H)
    if grand:                                                 # gold accents at the rail crossings
        for z in (0, depth - 1):
            c.set_micro_cell(W // 2, H // 2, z, KNOB)
    _knob(c, W, H // 2, depth)
    if w > 1:
        _knob(c, W // 2 - 1, H // 2, depth)                  # second leaf knob at the mullion
    return c


def build_gate(w=3, h=3, depth=4) -> DetailCanvas:
    """Heavy timber gate: thick planks + iron bands + big studs (courtyard/barn/keep)."""
    c = DetailCanvas()
    W, H = w * 9, h * 9
    c.fill_micro_box(0, 0, 0, W, H, depth, PANEL)
    for gx in range(0, W, 4):                                 # thick plank reveals
        for y in range(H):
            c.set_micro_cell(gx, y, depth - 1, AIR)
    for by in (int(H * 0.2), int(H * 0.55), int(H * 0.9)):    # heavy bands + studs
        c.fill_micro_box(0, by, depth - 1, W, 3, 1, IRON)
        for sx in range(2, W, 4):
            c.fill_micro_box(sx, by, depth - 1, 2, 1, 1, IRON)
    for z in (0, depth - 1):                                  # central ring
        c.set_micro_cell(W // 2, H // 2, z, KNOB)
    return c


_BUILDERS = {
    "door_plank": lambda: build_plank(1, 2),
    "door_iron":  lambda: build_iron(1, 2),
    "door_grand": lambda: build_panelled(2, 3, grand=True),
    "gate_timber": lambda: build_gate(3, 3),
}


# --------------------------------------------------------------------------- selection

def select_door(opening_w: int, purpose: str = "", lockable: bool = False,
                exterior: bool = False) -> str:
    """Pick the most appropriate catalog door for an opening. Deterministic, situation-driven:
    the SITUATION generally wins over the spec width (a bedroom gets a single door even if the spec
    drew a 2-wide opening), so the chosen door's width then drives the realized opening."""
    p = (purpose or "").lower()

    def has(*ks):
        return any(k in p for k in ks)

    # grand MAIN entrance first (a 2-leaf grand door — wins over gate even when wide)
    if (exterior and has("entry", "entrance", "foyer", "vestibule", "reception", "great hall", "main hall")) or \
       has("grand", "manor entrance", "temple", "throne", "ballroom"):
        return "door_grand"
    # explicit gate, or a very wide non-entrance opening
    if has("gate", "courtyard", "barn", "keep", "stable", "portcullis") or opening_w >= 3:
        return "gate_timber"
    # secure / utility rooms -> sturdy iron (lockable)
    if has("cellar", "vault", "storeroom", "store-room", "prison", "dungeon", "crypt", "armory"):
        return "door_iron"
    # humble single rooms -> plain plank (panel if it must lock, since plank isn't lockable)
    if has("bedroom", "closet", "servant", "pantry", "privy", "larder", "scullery", "nursery", "guest"):
        return "door_wood" if lockable else "door_plank"
    # otherwise: a wide interior opening is a double door, else a panel door
    if opening_w >= 2:
        return "door_wood_wide"
    return "door_wood"


def door_for_opening(width: int, purpose: str = "", lockable: bool = False, exterior: bool = False) -> DoorDef:
    return DOOR_CATALOG[select_door(width, purpose, lockable, exterior)]


def selected_door_for_portal(between, width: int, lockable: bool, story_height: int,
                             purpose_map: Dict[str, str]) -> DoorDef:
    """The catalog door the realizer will use for a door portal — shared by the shell (opening
    carve), the live placement, and the checks so all three agree. Falls back if the chosen door
    is taller than the wall."""
    exterior = "exterior" in between
    purpose = " ".join(purpose_map.get(r, "") for r in between if r != "exterior")
    dd = door_for_opening(width, purpose, lockable, exterior)
    if dd.height > story_height:                       # too tall for this wall — step down
        dd = DOOR_CATALOG["door_wood_wide"] if dd.width >= 2 else DOOR_CATALOG["door_wood"]
    return dd


# --------------------------------------------------------------------------- emit

def write_door(name: str) -> Path:
    canvas = _BUILDERS[name]()
    d = DOOR_CATALOG[name]
    rep = canvas.report()
    header = [
        "# ==========================================================",
        f"# name:         {name}",
        f"# display_name: {name.replace('_', ' ').title()}",
        "# category:     door",
        f"# style:        {d.style}",
        f"# bounds:       {d.width}W x {d.height}H  (hinge stile at X=0, knob on latch side)",
        f"# swing:        {d.swing}",
        f"# lockable:     {d.lockable}",
        f"# primitives:   {rep.cubes} C + {rep.subcubes} S + {rep.microcubes} M = {rep.total_voxels}",
        "# method:       structure_pipeline.doors",
        "# ==========================================================",
        "# Format: C cx cy cz Mat | S .. sx sy sz Mat | M .. mx my mz Mat",
        "",
    ]
    path = TEMPLATES_DIR / f"{name}.voxel"
    path.write_text("\n".join(header + canvas.to_voxel_lines()) + "\n", encoding="utf-8")
    return path


def main(argv=None) -> int:
    import sys
    from .geometry import template_cells, floating_components, measure_template
    for name in _GENERATED:
        p = write_door(name)
        fl = floating_components(template_cells(name))
        m = measure_template(name)
        flag = f"!! {len(fl)} FLOATING" if fl else "connected"
        dims = f"{m[0]:.2f}x{m[1]:.2f}x{m[2]:.2f}m" if m else "?"
        print(f"[doors] wrote {p.name:16s} {dims:18s} {flag}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
