#pragma once

#include "scene/CharacterSkeleton.h"
#include "graphics/Animation.h"
#include <string>
#include <vector>

namespace Phyxel {
namespace Scene {

/// Parameters for procedural humanoid skeleton generation.
struct HumanoidParams {
    float height = 1.8f;        ///< Total character height in world units
    float bulk = 1.0f;          ///< Width multiplier (1.0 = normal proportions)
    float headRatio = 0.12f;    ///< Head height as fraction of total height
    float torsoRatio = 0.30f;   ///< Torso height as fraction of total height
    float legRatio = 0.47f;     ///< Leg height as fraction of total height
    float armRatio = 0.38f;     ///< Arm length as fraction of total height
    float shoulderWidth = 0.35f;///< Half-width of shoulders (world units at bulk=1)
    float hipWidth = 0.15f;     ///< Half-width of hips (world units at bulk=1)
};

/// Parameters for procedural quadruped skeleton generation.
struct QuadrupedParams {
    float bodyLength = 1.0f;   ///< Spine length from shoulder to hip
    float legHeight = 0.6f;    ///< Total leg length
    float bodyWidth = 0.25f;   ///< Half-width of body
    float neckLength = 0.3f;   ///< Neck length
    float headSize = 0.15f;    ///< Head radius approximation
    float tailLength = 0.3f;   ///< Tail length (0 to omit)
};

/// Parameters for procedural arachnid/multi-legged skeleton generation.
struct ArachnidParams {
    int legCount = 8;          ///< Number of legs (must be even, 4-12)
    float bodyRadius = 0.2f;   ///< Radius of central body
    float legLength = 0.5f;    ///< Total leg length (upper + lower)
    float legSpread = 0.8f;    ///< How far legs spread outward (radians from vertical)
};

/// Generates CharacterSkeleton instances procedurally at runtime, without
/// requiring .anim files. Also generates simple locomotion animation clips.
///
/// Usage:
///   auto skeleton = ProceduralSkeleton::humanoid(HumanoidParams{.height = 2.0f});
///   auto walkClip = ProceduralSkeleton::humanoidWalkCycle(skeleton, 2.0f);
///
/// The output CharacterSkeleton has computed bone sizes, joint defs, and
/// voxel model shapes—ready to pass to VoxelCharacter::loadModel() or
/// PhysicsDriveMode::buildFromSkeleton().
class ProceduralSkeleton {
public:
    /// Generate a humanoid skeleton (~20 bones: hips, spine, chest, neck, head,
    /// upper/lower arms, hands, upper/lower legs, feet).
    static CharacterSkeleton humanoid(const HumanoidParams& params = {});

    /// Generate a quadruped skeleton (~18 bones: hips, spine, chest, neck, head,
    /// 4x upper/lower legs, optional tail).
    static CharacterSkeleton quadruped(const QuadrupedParams& params = {});

    /// Generate an arachnid/multi-legged skeleton (body + N legs x 2 segments).
    static CharacterSkeleton arachnid(const ArachnidParams& params = {});

    /// Generate a simple walk cycle animation for a humanoid skeleton.
    /// @param skeleton Must have been generated by humanoid().
    /// @param speed Walking speed in world units/second.
    /// @return An AnimationClip named "walk" with the given duration.
    static AnimationClip humanoidWalkCycle(const CharacterSkeleton& skeleton,
                                           float speed = 2.0f);

    /// Generate a simple idle animation for a humanoid skeleton (subtle breathing).
    static AnimationClip humanoidIdleCycle(const CharacterSkeleton& skeleton);

    /// Generate a simple walk cycle for a quadruped skeleton.
    static AnimationClip quadrupedWalkCycle(const CharacterSkeleton& skeleton,
                                            float speed = 2.0f);

    /// Generate a simple walk cycle for an arachnid skeleton.
    static AnimationClip arachnidWalkCycle(const CharacterSkeleton& skeleton,
                                            float speed = 1.5f);
};

} // namespace Scene
} // namespace Phyxel
