"""Asset metrics — the "understanding" layer for any `.voxel` template.

An AssetMetrics describes the asset's geometry and per-interaction-point
features (e.g., seat dimensions, doorknob position, container opening) in
local coordinates. The interaction pipeline uses it to (a) derive
initial-guess profile offsets for new characters and (b) run compatibility
checks (e.g., does the giant's hip width fit on this seat?).

Sidecar files live next to the `.voxel` template:
    resources/templates/chair_wood.voxel
    resources/templates/chair_wood.metrics.json     <-- generated by
                                                        tools/characterize_asset.py

All measurements are LOCAL to the asset (origin at the asset's (0,0,0)).
Units are metres; the engine's local-to-world transform places the asset.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Optional


SCHEMA_VERSION = "asset_metrics.v1"

# Voxel-primitive sizes in metres (matching engine convention)
_CUBE_SIZE = 1.0
_SUBCUBE_SIZE = 1.0 / 3.0
_MICROCUBE_SIZE = 1.0 / 9.0


# ---------------------------------------------------------------------------
# .voxel parsing
# ---------------------------------------------------------------------------

@dataclass
class VoxelBox:
    """A single voxel primitive expressed as a local-space AABB."""
    mn: tuple[float, float, float]   # min corner (x, y, z)
    mx: tuple[float, float, float]   # max corner
    material: str


@dataclass
class InteractionPointDecl:
    """An `interaction_point` line from the .voxel header."""
    point_id: str
    kind: str                        # "seat", "door", "container", etc.
    local_position: tuple[float, float, float]
    facing_yaw: float
    flags: str = "*"


# Regex for the metadata comment that declares interaction points.
_INTERACTION_POINT_RE = re.compile(
    r"#\s*interaction_point\s*:\s*"
    r"(?P<id>\S+)\s+(?P<kind>\S+)\s+"
    r"(?P<x>-?\d+\.?\d*)\s+(?P<y>-?\d+\.?\d*)\s+(?P<z>-?\d+\.?\d*)\s+"
    r"(?P<yaw>-?\d+\.?\d*)"
    r"(?:\s+(?P<flags>\S+))?",
    re.IGNORECASE,
)


def parse_voxel_template(path: Path) -> tuple[list[VoxelBox], list[InteractionPointDecl]]:
    """Parse a `.voxel` text file into (voxel boxes, interaction point declarations).

    The format (from existing engine loader, see e.g. resources/templates/chair_wood.voxel):
      - `#` introduces a comment; metadata uses `# key: value` lines.
      - `# interaction_point: <id> <kind> <x> <y> <z> <yaw> <flags>` declares an anchor.
      - `C px py pz material` is a 1m cube at local (px,py,pz).
      - `S px py pz sx sy sz material` is a 1/3m subcube at parent (px,py,pz) + sub (sx,sy,sz).
      - `M px py pz sx sy sz mx my mz material` is a 1/9m microcube similarly nested.
    """
    boxes: list[VoxelBox] = []
    points: list[InteractionPointDecl] = []
    raw = path.read_text(encoding="utf-8")
    for raw_line in raw.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#"):
            m = _INTERACTION_POINT_RE.search(line)
            if m:
                points.append(InteractionPointDecl(
                    point_id=m.group("id"),
                    kind=m.group("kind").lower(),
                    local_position=(float(m.group("x")), float(m.group("y")), float(m.group("z"))),
                    facing_yaw=float(m.group("yaw")),
                    flags=m.group("flags") or "*",
                ))
            continue
        parts = line.split()
        if not parts:
            continue
        tag = parts[0].upper()
        try:
            if tag == "C" and len(parts) >= 5:
                px, py, pz = float(parts[1]), float(parts[2]), float(parts[3])
                mat = parts[4]
                mn = (px, py, pz)
                mx = (px + _CUBE_SIZE, py + _CUBE_SIZE, pz + _CUBE_SIZE)
                boxes.append(VoxelBox(mn=mn, mx=mx, material=mat))
            elif tag == "S" and len(parts) >= 8:
                px, py, pz = float(parts[1]), float(parts[2]), float(parts[3])
                sx, sy, sz = float(parts[4]), float(parts[5]), float(parts[6])
                mat = parts[7]
                mn = (px + sx * _SUBCUBE_SIZE,
                      py + sy * _SUBCUBE_SIZE,
                      pz + sz * _SUBCUBE_SIZE)
                mx = (mn[0] + _SUBCUBE_SIZE, mn[1] + _SUBCUBE_SIZE, mn[2] + _SUBCUBE_SIZE)
                boxes.append(VoxelBox(mn=mn, mx=mx, material=mat))
            elif tag == "M" and len(parts) >= 11:
                px, py, pz = float(parts[1]), float(parts[2]), float(parts[3])
                sx, sy, sz = float(parts[4]), float(parts[5]), float(parts[6])
                mx_, my_, mz_ = float(parts[7]), float(parts[8]), float(parts[9])
                mat = parts[10]
                mn = (px + sx * _SUBCUBE_SIZE + mx_ * _MICROCUBE_SIZE,
                      py + sy * _SUBCUBE_SIZE + my_ * _MICROCUBE_SIZE,
                      pz + sz * _SUBCUBE_SIZE + mz_ * _MICROCUBE_SIZE)
                mx_b = (mn[0] + _MICROCUBE_SIZE, mn[1] + _MICROCUBE_SIZE, mn[2] + _MICROCUBE_SIZE)
                boxes.append(VoxelBox(mn=mn, mx=mx_b, material=mat))
        except ValueError:
            # Malformed numeric — skip silently; the engine loader is the authority.
            continue
    return boxes, points


def aabb_of(boxes: list[VoxelBox]) -> tuple[tuple[float, float, float],
                                            tuple[float, float, float]]:
    """Return overall (min, max) of a collection of voxel boxes."""
    if not boxes:
        return ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    mn = [float("inf")] * 3
    mx = [float("-inf")] * 3
    for b in boxes:
        for i in range(3):
            if b.mn[i] < mn[i]:
                mn[i] = b.mn[i]
            if b.mx[i] > mx[i]:
                mx[i] = b.mx[i]
    return (tuple(mn), tuple(mx))  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Per-kind feature extraction
# ---------------------------------------------------------------------------

@dataclass
class SeatFeatures:
    """Geometry-derived features of a `seat`-kind interaction point.

    All values in local-asset coordinates and metres.
    """
    seat_top_y: float            # Y of the top face of the contiguous seat slab
    seat_width_x: float          # X extent of contiguous seat-top voxels
    seat_depth_z: float          # Z extent of contiguous seat-top voxels
    seat_center: tuple[float, float, float]
    front_edge_z: float          # Z of the front face (along facing direction)
    backrest_height: float       # Y delta from seat top to top of backrest voxels (0 if none)
    backrest_present: bool

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["seat_center"] = list(self.seat_center)
        return d


@dataclass
class InteractionPointMetrics:
    """Per-point metrics in the sidecar file."""
    point_id: str
    kind: str
    local_position: tuple[float, float, float]
    facing_yaw: float
    features: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "point_id": self.point_id,
            "kind": self.kind,
            "local_position": list(self.local_position),
            "facing_yaw": self.facing_yaw,
            "features": self.features,
        }


@dataclass
class AssetMetrics:
    schema_version: str
    template_name: str
    overall_min: tuple[float, float, float]
    overall_max: tuple[float, float, float]
    interaction_points: list[InteractionPointMetrics] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "template_name": self.template_name,
            "overall_min": list(self.overall_min),
            "overall_max": list(self.overall_max),
            "interaction_points": [p.to_dict() for p in self.interaction_points],
        }

    @classmethod
    def from_file(cls, path: Path) -> "AssetMetrics":
        data = json.loads(path.read_text(encoding="utf-8"))
        schema = str(data.get("schema_version", ""))
        if schema != SCHEMA_VERSION:
            raise RuntimeError(
                f"unsupported asset metrics schema {schema!r}; expected {SCHEMA_VERSION!r}"
            )
        return cls(
            schema_version=schema,
            template_name=data["template_name"],
            overall_min=tuple(data["overall_min"]),
            overall_max=tuple(data["overall_max"]),
            interaction_points=[
                InteractionPointMetrics(
                    point_id=p["point_id"],
                    kind=p["kind"],
                    local_position=tuple(p["local_position"]),
                    facing_yaw=float(p["facing_yaw"]),
                    features=dict(p.get("features", {})),
                )
                for p in data.get("interaction_points", [])
            ],
        )


# ---------------------------------------------------------------------------
# Feature extractors per kind
# ---------------------------------------------------------------------------

def extract_seat_features(
    boxes: list[VoxelBox],
    point: InteractionPointDecl,
    *,
    y_tolerance: float = 0.05,
) -> SeatFeatures:
    """Compute seat-specific features from voxel geometry.

    Strategy:
      - The seat-top voxels are those whose `max.y` is within `y_tolerance` of
        the interaction-point Y (which by convention is the seat surface).
      - From that set, compute the XZ footprint and centre.
      - Anything above the seat top is candidate backrest geometry — measured
        by max-Y minus seat-top-Y.
    """
    ix, iy, iz = point.local_position
    seat_top_boxes = [b for b in boxes if abs(b.mx[1] - iy) <= y_tolerance]
    if not seat_top_boxes:
        # Fall back: take the boxes whose top face is highest while still <= seat Y.
        below = [b for b in boxes if b.mx[1] <= iy + y_tolerance]
        if below:
            top_y = max(b.mx[1] for b in below)
            seat_top_boxes = [b for b in below if abs(b.mx[1] - top_y) <= 1e-4]
    if not seat_top_boxes:
        return SeatFeatures(
            seat_top_y=iy, seat_width_x=0.0, seat_depth_z=0.0,
            seat_center=(ix, iy, iz), front_edge_z=iz,
            backrest_height=0.0, backrest_present=False,
        )

    xs_mn = min(b.mn[0] for b in seat_top_boxes)
    xs_mx = max(b.mx[0] for b in seat_top_boxes)
    zs_mn = min(b.mn[2] for b in seat_top_boxes)
    zs_mx = max(b.mx[2] for b in seat_top_boxes)
    top_y = max(b.mx[1] for b in seat_top_boxes)

    # Front edge: the voxel face the character approaches from. facing_yaw == 0
    # means the character faces +Z (forward), so the chair's front faces +Z too
    # and the front edge is at zs_mx; non-zero yaw rotates accordingly. For
    # axis-aligned chairs we approximate using the dominant facing axis.
    import math
    fy = float(point.facing_yaw)
    fx, fz = math.sin(fy), math.cos(fy)
    if abs(fz) >= abs(fx):
        front_edge_z = zs_mx if fz >= 0 else zs_mn
    else:
        # facing along ±X — front edge is X; pack into z field for now and
        # leave to consumer to interpret via facing.
        front_edge_z = xs_mx if fx >= 0 else xs_mn

    # Backrest: voxels above the seat top that overlap the seat footprint in XZ.
    backrest = [
        b for b in boxes
        if b.mn[1] >= top_y - 1e-4
        and b.mx[0] > xs_mn and b.mn[0] < xs_mx
        and b.mx[2] > zs_mn and b.mn[2] < zs_mx
    ]
    if backrest:
        backrest_top = max(b.mx[1] for b in backrest)
        backrest_height = max(0.0, backrest_top - top_y)
        backrest_present = backrest_height > 1e-3
    else:
        backrest_height = 0.0
        backrest_present = False

    return SeatFeatures(
        seat_top_y=top_y,
        seat_width_x=xs_mx - xs_mn,
        seat_depth_z=zs_mx - zs_mn,
        seat_center=((xs_mn + xs_mx) * 0.5, top_y, (zs_mn + zs_mx) * 0.5),
        front_edge_z=front_edge_z,
        backrest_height=backrest_height,
        backrest_present=backrest_present,
    )


@dataclass
class DoorFeatures:
    """Geometry-derived features of a `door_handle`-kind interaction point.

    All values in local-asset coordinates and metres. The handle position is
    the interaction point itself; the panel dims describe the door leaf the
    character pushes/pulls.
    """
    handle_y: float                  # Y of the handle (== interaction point Y)
    handle_xz: tuple[float, float]   # X, Z of the handle
    panel_width: float               # X extent of the door panel
    panel_height: float              # Y extent of the door panel
    panel_depth: float               # Z extent of the door panel
    panel_center: tuple[float, float, float]
    hinge_xz: tuple[float, float]    # X, Z of the hinge edge (panel's pivot side)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["handle_xz"] = list(self.handle_xz)
        d["panel_center"] = list(self.panel_center)
        d["hinge_xz"] = list(self.hinge_xz)
        return d


def extract_door_features(
    boxes: list[VoxelBox],
    point: InteractionPointDecl,
) -> DoorFeatures:
    """Compute door-specific features.

    The hinge edge is approximated as the panel-AABB X edge that is *farthest*
    from the handle (handle is on the latch side, hinge on the opposite side).
    """
    hx, hy, hz = point.local_position
    if not boxes:
        return DoorFeatures(
            handle_y=hy, handle_xz=(hx, hz),
            panel_width=0.0, panel_height=0.0, panel_depth=0.0,
            panel_center=(hx, hy, hz), hinge_xz=(hx, hz),
        )
    pmn, pmx = aabb_of(boxes)
    width = pmx[0] - pmn[0]
    height = pmx[1] - pmn[1]
    depth = pmx[2] - pmn[2]
    centre = ((pmn[0] + pmx[0]) * 0.5,
              (pmn[1] + pmx[1]) * 0.5,
              (pmn[2] + pmx[2]) * 0.5)
    # Hinge on opposite X edge from the handle.
    hinge_x = pmn[0] if abs(hx - pmx[0]) < abs(hx - pmn[0]) else pmx[0]
    # Hinge Z assumed coincident with panel's near Z (whichever side the
    # handle is nearer to; doors are usually thin in Z).
    hinge_z = pmn[2] if abs(hz - pmn[2]) <= abs(hz - pmx[2]) else pmx[2]
    return DoorFeatures(
        handle_y=hy,
        handle_xz=(hx, hz),
        panel_width=width,
        panel_height=height,
        panel_depth=depth,
        panel_center=centre,
        hinge_xz=(hinge_x, hinge_z),
    )


def characterize_asset(template_path: Path) -> AssetMetrics:
    """Top-level entry: parse a .voxel and produce its metrics record.

    For interaction kinds we don't yet support (container, liftable),
    the per-point `features` field is left empty — the kind's own
    extractor can be added later without breaking the file format.
    """
    boxes, points = parse_voxel_template(template_path)
    overall_min, overall_max = aabb_of(boxes)
    ipms: list[InteractionPointMetrics] = []
    for p in points:
        features: dict[str, Any] = {}
        if p.kind == "seat":
            features = extract_seat_features(boxes, p).to_dict()
        elif p.kind == "door_handle":
            features = extract_door_features(boxes, p).to_dict()
        ipms.append(InteractionPointMetrics(
            point_id=p.point_id,
            kind=p.kind,
            local_position=p.local_position,
            facing_yaw=p.facing_yaw,
            features=features,
        ))
    return AssetMetrics(
        schema_version=SCHEMA_VERSION,
        template_name=template_path.stem,
        overall_min=overall_min,
        overall_max=overall_max,
        interaction_points=ipms,
    )


# ---------------------------------------------------------------------------
# Stage 1 validation gate
# ---------------------------------------------------------------------------

# Per-kind required feature keys. Stage 4 will not accept an asset whose
# selected interaction point is missing any of these.
_REQUIRED_FEATURES: dict[str, tuple[str, ...]] = {
    "seat":        ("seat_top_y", "seat_width_x", "seat_depth_z", "seat_center"),
    "door_handle": ("handle_y", "handle_xz", "panel_width", "panel_height", "hinge_xz"),
}


@dataclass(frozen=True)
class AssetIssue:
    """One validation problem found by :func:`validate_asset_metrics`.

    ``severity`` is ``"error"`` (must fix before tuner runs) or ``"warn"``
    (suspicious but not fatal). ``point_id`` is the point that failed, or
    empty string for asset-level issues.
    """
    severity: str
    point_id: str
    rule_id: str
    message: str


def _is_finite_xyz(v: Any) -> bool:
    if not isinstance(v, (list, tuple)) or len(v) != 3:
        return False
    try:
        return all(float(x) == float(x) and abs(float(x)) < 1e6 for x in v)  # NaN-safe
    except (TypeError, ValueError):
        return False


def validate_asset_metrics(metrics: AssetMetrics) -> list[AssetIssue]:
    """Stage 1 gate. Empty result = asset is ratified for downstream stages."""
    issues: list[AssetIssue] = []

    if not metrics.template_name:
        issues.append(AssetIssue("error", "", "TEMPLATE_NAME_MISSING",
                                 "AssetMetrics has no template_name."))

    if not _is_finite_xyz(metrics.overall_min) or not _is_finite_xyz(metrics.overall_max):
        issues.append(AssetIssue("error", "", "AABB_INVALID",
                                 "Overall AABB is missing or non-finite."))
    else:
        for i, axis in enumerate("xyz"):
            if metrics.overall_max[i] < metrics.overall_min[i]:
                issues.append(AssetIssue("error", "", "AABB_INVERTED",
                                         f"overall_max.{axis} < overall_min.{axis}"))

    if not metrics.interaction_points:
        issues.append(AssetIssue("error", "", "NO_INTERACTION_POINTS",
                                 "Template declares no interaction points."))
        return issues

    seen_ids: set[str] = set()
    for p in metrics.interaction_points:
        pid = p.point_id or "<unnamed>"
        if not p.point_id:
            issues.append(AssetIssue("error", pid, "POINT_ID_MISSING",
                                     "Interaction point is missing point_id."))
        if p.point_id in seen_ids:
            issues.append(AssetIssue("error", pid, "POINT_ID_DUPLICATE",
                                     f"Duplicate interaction point id '{p.point_id}'."))
        seen_ids.add(p.point_id)

        if not _is_finite_xyz(p.local_position):
            issues.append(AssetIssue("error", pid, "POSITION_INVALID",
                                     "local_position is missing or non-finite."))
        else:
            # Position should lie inside the asset's AABB (allow small slack).
            mn, mx = metrics.overall_min, metrics.overall_max
            slack = 0.05
            for i, axis in enumerate("xyz"):
                if p.local_position[i] < mn[i] - slack or p.local_position[i] > mx[i] + slack:
                    issues.append(AssetIssue(
                        "warn", pid, "POSITION_OUTSIDE_AABB",
                        f"local_position.{axis}={p.local_position[i]:.3f} "
                        f"outside asset AABB [{mn[i]:.3f}, {mx[i]:.3f}]"))

        try:
            yaw = float(p.facing_yaw)
            if yaw != yaw or abs(yaw) > 4.0 * 3.141592653589793:
                raise ValueError
        except (TypeError, ValueError):
            issues.append(AssetIssue("warn", pid, "FACING_YAW_SUSPICIOUS",
                                     f"facing_yaw={p.facing_yaw!r} not a finite radian value."))

        required = _REQUIRED_FEATURES.get(p.kind, ())
        if required and not p.features:
            issues.append(AssetIssue(
                "error", pid, "FEATURES_MISSING",
                f"Kind '{p.kind}' requires features {list(required)} but none were extracted."))
        else:
            missing = [k for k in required if k not in p.features]
            if missing:
                issues.append(AssetIssue(
                    "error", pid, "FEATURES_INCOMPLETE",
                    f"Kind '{p.kind}' is missing required feature keys: {missing}"))
            # Kind-specific sanity checks
            if p.kind == "seat" and p.features:
                w = float(p.features.get("seat_width_x") or 0.0)
                d = float(p.features.get("seat_depth_z") or 0.0)
                if w <= 0.0 or d <= 0.0:
                    issues.append(AssetIssue(
                        "error", pid, "SEAT_DIMS_NON_POSITIVE",
                        f"seat_width_x={w:.3f}, seat_depth_z={d:.3f} must be > 0."))
                top = p.features.get("seat_top_y")
                if top is not None and float(top) < metrics.overall_min[1] - 0.05:
                    issues.append(AssetIssue(
                        "warn", pid, "SEAT_TOP_BELOW_AABB",
                        f"seat_top_y={top} is below the asset's minimum Y."))
            if p.kind == "door_handle" and p.features:
                pw = float(p.features.get("panel_width") or 0.0)
                ph = float(p.features.get("panel_height") or 0.0)
                if pw <= 0.0 or ph <= 0.0:
                    issues.append(AssetIssue(
                        "error", pid, "DOOR_PANEL_NON_POSITIVE",
                        f"panel_width={pw:.3f}, panel_height={ph:.3f} must be > 0."))

    return issues


def asset_provenance(metrics: AssetMetrics, point_id: str) -> dict[str, Any]:
    """Compact snapshot of one interaction point's input for embedding in a
    persisted profile. Stage 4 calls this to record exactly which AssetMetrics
    point a profile was tuned against."""
    for p in metrics.interaction_points:
        if p.point_id == point_id:
            return {
                "template_name": metrics.template_name,
                "schema_version": metrics.schema_version,
                "point_id": p.point_id,
                "kind": p.kind,
                "local_position": list(p.local_position),
                "facing_yaw": p.facing_yaw,
                "features": dict(p.features),
            }
    raise KeyError(f"point_id '{point_id}' not in asset '{metrics.template_name}'")


__all__ = [
    "SCHEMA_VERSION",
    "VoxelBox",
    "InteractionPointDecl",
    "SeatFeatures",
    "DoorFeatures",
    "InteractionPointMetrics",
    "AssetMetrics",
    "AssetIssue",
    "parse_voxel_template",
    "extract_seat_features",
    "extract_door_features",
    "characterize_asset",
    "validate_asset_metrics",
    "asset_provenance",
]
