#pragma once

#include <string>
#include <vector>
#include <glm/glm.hpp>
#include <nlohmann/json.hpp>
#include "core/LocationRegistry.h"

namespace Phyxel {

class ChunkManager;

namespace Core {

// ============================================================================
// Types
// ============================================================================

/// Voxel resolution level.
enum class VoxelLevel { Cube, Subcube, Microcube };

/// Detail level for composite structure generation.
/// Rough = cube-only, Detailed = cube + subcube trim, Fine = + microcube accents (future).
enum class DetailLevel { Rough, Detailed, Fine };

/// A single voxel to be placed in the world.
struct VoxelPlacement {
    glm::ivec3 position{0};      ///< World-space cube position
    std::string material;         ///< Material name (e.g. "Stone", "Wood")
    VoxelLevel level = VoxelLevel::Cube;
    glm::ivec3 subcubePos{0};    ///< Subcube offset within cube (0-2 each axis), used when level >= Subcube
    glm::ivec3 microcubePos{0};  ///< Microcube offset within subcube (0-2 each axis), used when level == Microcube
};

/// A location marker generated by a structure (auto-registered).
struct LocationMarker {
    std::string id;
    std::string name;
    glm::vec3 position{0.0f};
    float radius = 3.0f;
    LocationType type = LocationType::Custom;
};

/// Cardinal facing direction for structures.
enum class Facing { North, East, South, West };

/// Result of a structure generation.
struct StructureResult {
    std::vector<VoxelPlacement> voxels;
    std::vector<LocationMarker> locations;
};

/// Result of placing a structure into the world.
struct PlacementResult {
    int placed = 0;
    int failed = 0;
    std::vector<LocationMarker> locations;
};

// ============================================================================
// Material palette for composite structures
// ============================================================================

struct MaterialPalette {
    std::string wall   = "Stone";
    std::string floor  = "Wood";
    std::string roof   = "Wood";
    std::string door   = "";        ///< Empty = air (opening)
    std::string window = "";        ///< Empty = air (opening)
    std::string stairs = "Stone";
    std::string furniture = "Wood";

    static MaterialPalette fromJson(const nlohmann::json& j);
};

// ============================================================================
// StructureGenerator
// ============================================================================

class StructureGenerator {
public:
    // -- Facing helpers --
    static Facing facingFromString(const std::string& s);
    static std::string facingToString(Facing f);

    // -- Detail level helpers --
    static DetailLevel detailLevelFromString(const std::string& s);
    static std::string detailLevelToString(DetailLevel d);

    /// Rotate a local-coordinate position around origin (0,0,0) for a given facing.
    /// North = identity, East = 90° CW, South = 180°, West = 270° CW.
    /// `bounds` is the {width, depth} of the structure (needed for rotation pivot).
    static glm::ivec3 rotateLocal(const glm::ivec3& local, Facing facing, int width, int depth);

    // =======================================================================
    // Primitives — all return voxels in world coordinates
    // =======================================================================

    /// Solid or hollow box.
    static StructureResult generateBox(const glm::ivec3& pos, int width, int height, int depth,
                                       const std::string& material, bool hollow = false);

    /// Four walls (no floor or ceiling).
    static StructureResult generateWalls(const glm::ivec3& pos, int width, int height, int depth,
                                         const std::string& material, int thickness = 1);

    /// Single-layer floor/platform.
    static StructureResult generateFloor(const glm::ivec3& pos, int width, int depth,
                                         const std::string& material);

    /// Enclosed room (floor + walls + ceiling).
    static StructureResult generateRoom(const glm::ivec3& pos, int width, int height, int depth,
                                        const MaterialPalette& materials);

    /// Carve a rectangular doorway. Removes voxels; returns empty placements at those positions.
    static std::vector<glm::ivec3> generateDoorOpening(const glm::ivec3& wallBase,
                                                        int width = 2, int height = 3);

    /// Carve a rectangular window opening.
    static std::vector<glm::ivec3> generateWindowOpening(const glm::ivec3& wallBase,
                                                          int width = 2, int height = 2);

    /// Ascending staircase along +X direction (rotated by facing).
    static StructureResult generateStaircase(const glm::ivec3& pos, Facing facing,
                                             int height, int width = 2,
                                             const std::string& material = "Stone");

    /// Subcube-resolution staircase: 3 subcube steps per full block height.
    /// Each step rises 1/3 of a block and extends 1/3 of a block deep.
    static StructureResult generateSubcubeStaircase(const glm::ivec3& pos, Facing facing,
                                                     int height, int width = 2,
                                                     const std::string& material = "Stone");

    // -- Subcube detail primitives --

    /// Subcube window frame surround (placed around an existing opening).
    static StructureResult generateWindowFrame(const glm::ivec3& pos, Facing facing,
                                                int width = 2, int height = 2,
                                                const std::string& material = "Wood");

    /// Subcube door frame surround (placed around an existing opening).
    static StructureResult generateDoorFrame(const glm::ivec3& pos, Facing facing,
                                              int width = 2, int height = 3,
                                              const std::string& material = "Wood");

    /// Subcube railing / bannister along a ledge.
    static StructureResult generateRailing(const glm::ivec3& pos, Facing facing,
                                            int length = 4,
                                            const std::string& material = "Wood");

    /// Half-height wall strip built from subcubes (e.g. knee wall, parapet).
    static StructureResult generateHalfWall(const glm::ivec3& pos, Facing facing,
                                             int length = 4,
                                             const std::string& material = "Stone");

    /// Pitched roof using subcubes (gable along local X, ridge along center).
    static StructureResult generatePitchedRoof(const glm::ivec3& pos, Facing facing,
                                                int width = 8, int depth = 10,
                                                const std::string& material = "Wood");

    // -- Furniture --

    /// 3-wide table (top on 4 legs).
    static StructureResult generateTable(const glm::ivec3& pos, Facing facing,
                                         const std::string& material = "Wood");

    /// Single chair (seat + back).
    static StructureResult generateChair(const glm::ivec3& pos, Facing facing,
                                         const std::string& material = "Wood");

    /// Bar/shop counter (length along X in local, rotated by facing).
    static StructureResult generateCounter(const glm::ivec3& pos, Facing facing,
                                           int length = 4,
                                           const std::string& material = "Wood");

    /// Bed (2 wide, 3 long).
    static StructureResult generateBed(const glm::ivec3& pos, Facing facing,
                                       const std::string& material = "Wood");

    // =======================================================================
    // Composites — high-level structure generators
    // =======================================================================

    /// Simple house: 4 walls + floor + flat roof + door + optional windows + furniture.
    static StructureResult generateHouse(const glm::ivec3& pos, int width, int depth, int height,
                                         const MaterialPalette& materials, Facing facing = Facing::South,
                                         int windows = 2, bool furnished = true,
                                         DetailLevel detail = DetailLevel::Detailed);

    /// Multi-room tavern: main hall + bar + tables + optional upper floor.
    static StructureResult generateTavern(const glm::ivec3& pos, int width, int depth, int stories,
                                          const MaterialPalette& materials, Facing facing = Facing::South,
                                          bool furnished = true,
                                          DetailLevel detail = DetailLevel::Detailed);

    /// Freestanding wall segment between two points.
    static StructureResult generateWallSegment(const glm::ivec3& start, const glm::ivec3& end,
                                               int height, const std::string& material, int thickness = 1);

    /// Cylindrical/octagonal tower with door + internal staircase.
    static StructureResult generateTower(const glm::ivec3& pos, int radius, int height,
                                         const std::string& material, Facing facing = Facing::South,
                                         DetailLevel detail = DetailLevel::Detailed);

    // =======================================================================
    // JSON-driven generation
    // =======================================================================

    /// Parse a structure definition from JSON and generate voxels.
    static StructureResult generateFromJson(const nlohmann::json& def);

    /// Get descriptions of all available structure types and their parameters.
    static nlohmann::json getStructureTypes();

    // =======================================================================
    // Placement into world
    // =======================================================================

    /// Place generated voxels into the chunk manager. Respects 100k limit.
    static PlacementResult place(ChunkManager* chunkManager, const StructureResult& structure);

    /// Remove voxels at the given positions (for door/window openings).
    static int removeVoxels(ChunkManager* chunkManager, const std::vector<glm::ivec3>& positions);

private:
    /// Apply rotation + world offset to a StructureResult that was built in local coords.
    static void transformResult(StructureResult& result, const glm::ivec3& worldOrigin,
                                Facing facing, int width, int depth);
};

} // namespace Core
} // namespace Phyxel
