#pragma once

#include <string>
#include <vector>
#include <glm/glm.hpp>
#include <nlohmann/json.hpp>
#include "core/LocationRegistry.h"

namespace Phyxel {

class ChunkManager;

namespace Core {

// ============================================================================
// Types
// ============================================================================

/// Voxel resolution level.
enum class VoxelLevel { Cube, Subcube, Microcube };

/// Detail level for composite structure generation.
/// Rough = cube-only, Detailed = cube + subcube trim, Fine = + microcube accents (future).
enum class DetailLevel { Rough, Detailed, Fine };

/// A single voxel to be placed in the world.
struct VoxelPlacement {
    glm::ivec3 position{0};      ///< World-space cube position
    std::string material;         ///< Material name (e.g. "Stone", "Wood")
    VoxelLevel level = VoxelLevel::Cube;
    glm::ivec3 subcubePos{0};    ///< Subcube offset within cube (0-2 each axis), used when level >= Subcube
    glm::ivec3 microcubePos{0};  ///< Microcube offset within subcube (0-2 each axis), used when level == Microcube
};

/// A location marker generated by a structure (auto-registered).
struct LocationMarker {
    std::string id;
    std::string name;
    glm::vec3 position{0.0f};
    float radius = 3.0f;
    LocationType type = LocationType::Custom;
};

/// Cardinal facing direction for structures.
enum class Facing { North, East, South, West };

/// Result of a structure generation.
struct StructureResult {
    std::vector<VoxelPlacement>  voxels;
    std::vector<LocationMarker>  locations;
};

/// Result of placing a structure into the world.
struct PlacementResult {
    int placed = 0;
    int failed = 0;
    /// Cells whose write DISPLACED pre-existing solid material. Placement is
    /// nominally additive, but a write at a finer tier replaces whatever coarser
    /// voxel occupied the same space — that is how a pass running AFTER the shell
    /// (a chimney stack threading a floor slab) can silently eat structure the
    /// shell-side validators already certified. A destructive write must declare
    /// itself so a gate can decide whether it broke anything.
    int displaced = 0;
    std::vector<glm::ivec3> displacedSample;   ///< first few, for diagnosis (capped)
    std::vector<LocationMarker> locations;
};

// ============================================================================
// Material palette for composite structures
// ============================================================================

struct MaterialPalette {
    std::string wall   = "Stone";
    std::string floor  = "Wood";
    std::string roof   = "WoodShingle";
    std::string door   = "";        ///< Empty = air (opening)
    std::string window = "";        ///< Empty = air (opening)
    std::string stairs = "Stone";
    std::string furniture = "Wood";

    static MaterialPalette fromJson(const nlohmann::json& j);
};

// ============================================================================
// StructureGenerator
// ============================================================================

class StructureGenerator {
public:
    // -- Facing helpers --
    static Facing facingFromString(const std::string& s);
    static std::string facingToString(Facing f);

    // -- Detail level helpers --
    static DetailLevel detailLevelFromString(const std::string& s);
    static std::string detailLevelToString(DetailLevel d);

    /// Rotate a local-coordinate position around origin (0,0,0) for a given facing.
    /// North = identity, East = 90° CW, South = 180°, West = 270° CW.
    /// `bounds` is the {width, depth} of the structure (needed for rotation pivot).
    static glm::ivec3 rotateLocal(const glm::ivec3& local, Facing facing, int width, int depth);

    // =======================================================================
    // Primitives — all return voxels in world coordinates
    // =======================================================================

    /// Solid or hollow box.
    static StructureResult generateBox(const glm::ivec3& pos, int width, int height, int depth,
                                       const std::string& material, bool hollow = false);

    /// Four walls (no floor or ceiling).
    static StructureResult generateWalls(const glm::ivec3& pos, int width, int height, int depth,
                                         const std::string& material, int thickness = 1);

    /// Single-layer floor/platform.
    static StructureResult generateFloor(const glm::ivec3& pos, int width, int depth,
                                         const std::string& material);

    /// Enclosed room (floor + walls + ceiling).
    static StructureResult generateRoom(const glm::ivec3& pos, int width, int height, int depth,
                                        const MaterialPalette& materials);

    /// Carve a rectangular doorway. Removes voxels; returns empty placements at those positions.
    static std::vector<glm::ivec3> generateDoorOpening(const glm::ivec3& wallBase,
                                                        int width = 2, int height = 3);

    /// Carve a rectangular window opening.
    static std::vector<glm::ivec3> generateWindowOpening(const glm::ivec3& wallBase,
                                                          int width = 2, int height = 2);

    /// Ascending staircase along +X direction (rotated by facing).
    static StructureResult generateStaircase(const glm::ivec3& pos, Facing facing,
                                             int height, int width = 2,
                                             const std::string& material = "Stone");

    /// Subcube-resolution staircase: 3 subcube steps per full block height.
    /// Each step rises 1/3 of a block and extends 1/3 of a block deep.
    static StructureResult generateSubcubeStaircase(const glm::ivec3& pos, Facing facing,
                                                     int height, int width = 2,
                                                     const std::string& material = "Stone");

    // -- Subcube detail primitives --

    /// Subcube window frame surround (placed around an existing opening).
    static StructureResult generateWindowFrame(const glm::ivec3& pos, Facing facing,
                                                int width = 2, int height = 2,
                                                const std::string& material = "Wood");

    /// Subcube door frame surround (placed around an existing opening).
    static StructureResult generateDoorFrame(const glm::ivec3& pos, Facing facing,
                                              int width = 2, int height = 3,
                                              const std::string& material = "Wood");

    /// Subcube railing / bannister along a ledge.
    static StructureResult generateRailing(const glm::ivec3& pos, Facing facing,
                                            int length = 4,
                                            const std::string& material = "Wood");

    /// Half-height wall strip built from subcubes (e.g. knee wall, parapet).
    static StructureResult generateHalfWall(const glm::ivec3& pos, Facing facing,
                                             int length = 4,
                                             const std::string& material = "Stone");

    /// Pitched roof using subcubes (gable along local X, ridge along center).
    static StructureResult generatePitchedRoof(const glm::ivec3& pos, Facing facing,
                                                int width = 8, int depth = 10,
                                                const std::string& material = "Wood");

    // -- Furniture --

    /// 3-wide table (top on 4 legs).
    static StructureResult generateTable(const glm::ivec3& pos, Facing facing,
                                         const std::string& material = "Wood");

    /// Single chair (seat + back).
    static StructureResult generateChair(const glm::ivec3& pos, Facing facing,
                                         const std::string& material = "Wood");

    /// Bar/shop counter (length along X in local, rotated by facing).
    static StructureResult generateCounter(const glm::ivec3& pos, Facing facing,
                                           int length = 4,
                                           const std::string& material = "Wood");

    /// Bed (2 wide, 3 long).
    static StructureResult generateBed(const glm::ivec3& pos, Facing facing,
                                       const std::string& material = "Wood");

    /// Freestanding wall segment between two points.
    /// NOTE: the v1 COMPOSITE building generators (house/tavern/tower, BuildingSpec)
    /// were REMOVED — generated buildings come from Structure Generation v2
    /// (StructureBuildService: BuildingProgram + StyleProfile -> StructureRealizer).
    /// This class keeps the deterministic PRIMITIVES + placement utilities only.
    static StructureResult generateWallSegment(const glm::ivec3& start, const glm::ivec3& end,
                                               int height, const std::string& material, int thickness = 1);

    // =======================================================================
    // JSON-driven generation (primitives only)
    // =======================================================================

    /// Parse a PRIMITIVE structure definition from JSON and generate voxels
    /// (wall/room/box/staircase/furniture/frames/pitched_roof...). Composite
    /// building types are handled by StructureBuildService (v2).
    static StructureResult generateFromJson(const nlohmann::json& def);

    /// Get descriptions of all available structure types and their parameters.
    static nlohmann::json getStructureTypes();

    // =======================================================================
    // Placement into world
    // =======================================================================

    /// Place generated voxels into the chunk manager, incrementally (in bounded steps).
    /// No silent size cap — large structures place fully; result carries true placed/failed.
    static PlacementResult place(ChunkManager* chunkManager, const StructureResult& structure);

    /// place_chimney (#14): plan a masonry chimney STACK as MICROCUBE voxels, from a vented hearth up
    /// THROUGH the roof, clearing the ridge for draught. `cx,cz` = the stack centre in WORLD MICRO
    /// units; the stack rises from `baseMicroY` to `topMicroY` (use roof-apex + the grounded ~0.56 m /
    /// 5-micro clearance per the 3-2-10 rule). A 5-micro (~0.56 m) square stack with an inner 3x3 FLUE
    /// VOID, capped solid at the top `capRows` rows (the pot, hiding the flue). Returns Stone microcube
    /// placements; deterministic + continuous (every micro-Y in [base,top] carries the stack ring).
    /// Testable in isolation (no engine). See docs/structure-generation/placers/14_place_chimney.md.
    static StructureResult planChimneyStack(int cx, int cz, int baseMicroY, int topMicroY,
                                            const std::string& material = "Stone", int capRows = 2);

    /// Ridge clearance for a chimney top, in MICRO cells: how far ABOVE the roof apex the stack must
    /// rise. 6 micro = 0.667 m >= the 2 ft (0.610 m) minimum of the 3-2-10 rule (IRC R1003.9). Shared
    /// by the build handler and the test so the grounded value can't silently regress below 2 ft.
    /// (5 micro / 0.556 m FAILS the 2 ft floor — grounding-auditor 2026-06-28.)
    static constexpr int kChimneyRidgeClearanceMicro = 6;

    /// Remove voxels at the given positions (for door/window openings).
    static int removeVoxels(ChunkManager* chunkManager, const std::vector<glm::ivec3>& positions);

    /// prepare_pad (#2) decision: choose a level build-pad height from the terrain
    /// tops under a footprint. The MEDIAN top minimizes total cut + fill and is robust
    /// to a few stray high/low voxels. Pure + unit-testable; the caller applies the
    /// cut (remove above) + fill (add below) to the live world. Empty -> 0.
    static int planPadLevel(std::vector<int> cellTops);

private:
    /// Apply rotation + world offset to a StructureResult that was built in local coords.
    static void transformResult(StructureResult& result, const glm::ivec3& worldOrigin,
                                Facing facing, int width, int depth);
};

} // namespace Core
} // namespace Phyxel
