// GENERATED by tools/gen_grass_site_order.py — DO NOT EDIT BY HAND.
// C++ mirror of shaders/grass_sites.glsl. Same table, so the packing unit test measures the sites
// the shader actually uses rather than a re-derivation of them.
#pragma once

#include <cstdint>

namespace Phyxel {
namespace Graphics {

/// Cells per voxel axis; blades occupy distinct cells of this world-aligned lattice.
inline constexpr uint32_t kGrassGrid = 16;
inline constexpr uint32_t kGrassSiteCount = 256;
inline constexpr float    kGrassPitch = 0.0625f;

/// Cseq in the spacing guarantee sepGuaranteed(N) = kGrassSeqSep/sqrt(N) - 2*jitter.
/// MEASURED from the table below by the generator — do not hand-edit either independently.
inline constexpr float    kGrassSeqSep = 0.7099f;

/// Progressive blue-noise ordering: every prefix is well-spread, so thinning the field to N blades
/// is just taking the first N entries.
inline constexpr uint8_t kGrassSiteOrder[kGrassSiteCount] = {
      0, 136,   8, 128,  68,  76, 196, 204,   4,  12,  64,  72, 132, 140, 192, 200,
     34,  38,  42,  46,  98, 102, 106, 110, 162, 166, 170, 174, 226, 230, 234, 238,
      2,   6,  10,  14,  32,  36,  40,  44,  66,  70,  74,  78,  96, 100, 104, 108,
    130, 134, 138, 142, 160, 164, 168, 172, 194, 198, 202, 206, 224, 228, 232, 236,
     17,  19,  21,  23,  25,  27,  29,  31,  49,  51,  53,  55,  57,  59,  61,  63,
     81,  83,  85,  87,  89,  91,  93,  95, 113, 115, 117, 119, 121, 123, 125, 127,
    145, 147, 149, 151, 153, 155, 157, 159, 177, 179, 181, 183, 185, 187, 189, 191,
    209, 211, 213, 215, 217, 219, 221, 223, 241, 243, 245, 247, 249, 251, 253, 255,
      1,   3,   5,   7,   9,  11,  13,  15,  16,  18,  20,  22,  24,  26,  28,  30,
     33,  35,  37,  39,  41,  43,  45,  47,  48,  50,  52,  54,  56,  58,  60,  62,
     65,  67,  69,  71,  73,  75,  77,  79,  80,  82,  84,  86,  88,  90,  92,  94,
     97,  99, 101, 103, 105, 107, 109, 111, 112, 114, 116, 118, 120, 122, 124, 126,
    129, 131, 133, 135, 137, 139, 141, 143, 144, 146, 148, 150, 152, 154, 156, 158,
    161, 163, 165, 167, 169, 171, 173, 175, 176, 178, 180, 182, 184, 186, 188, 190,
    193, 195, 197, 199, 201, 203, 205, 207, 208, 210, 212, 214, 216, 218, 220, 222,
    225, 227, 229, 231, 233, 235, 237, 239, 240, 242, 244, 246, 248, 250, 252, 254
};

} // namespace Graphics
} // namespace Phyxel
