#include <gtest/gtest.h>

#include <iostream>
#include <string>
#include <vector>

#include "core/BuildingProgram.h"
#include "core/StructureRealizer.h"
#include "core/StyleProfile.h"
#include "core/TraversalProbe.h"
#include "core/RoomLayout.h"

// ============================================================================
// Building Validation Harness — runs the building pipeline across a CORPUS of varied
// programs and reports a PASS/FAIL matrix per validation layer. This is the quality-
// tracking / sign-off instrument: "N of M cases pass; here are the failures and why."
// It is the reusable strict-validation infrastructure — later placers add cases + layers.
//
// Layers checked (v1, shell + circulation):
//   build    — realizeShell succeeds, non-empty.
//   floors   — L2: every room on every story has a floor to stand on (no fall-through).
//   reach    — L3: a character-box (TraversalProbe) climbs from the ground floor to the
//              TOP floor (every floor reachable). The hard one; where multi-story bugs live.
// (Furniture per-story / KI-2 is a handler concern — a future harness layer, noted in the ledger.)
// ============================================================================

using namespace Phyxel::Core;

namespace {

StyleProfile harnessStyle() {
    StyleProfileRegistry reg;
    reg.loadFromJson(nlohmann::json::parse(R"({
        "timber_cottage": {
            "roof_style": "gable", "foundation": "crawlspace",
            "thickness": { "exterior_wall": 0.333, "interior_wall": 0.222,
                           "foundation_wall": 0.667, "floor": 0.333, "ceiling": 0.222 },
            "materials": { "structure": "Wood", "floor": "Wood", "roof": "Wood", "foundation": "Stone" },
            "roof": { "pitch": 0.8 }
        }
    })"));
    return *reg.get("timber_cottage");
}

// A uniform-height tower: `stories` floors of height 3 over a w×d footprint, an exterior door
// on story 0, and (optionally) a stair on each floor to the next at well [1,2,2,6].
BuildingProgram tower(int stories, int w, int d, const std::string& form,
                      const std::string& substructure, bool withStairs) {
    nlohmann::json j;
    j["name"] = "case"; j["style"] = "timber_cottage";
    j["footprint"] = nlohmann::json::array({w, d});
    j["substructure"] = substructure; j["roof_style"] = "gable";
    j["stories"] = nlohmann::json::array();
    for (int s = 0; s < stories; ++s) {
        nlohmann::json room;
        room["id"] = "r" + std::to_string(s);
        room["rect"] = nlohmann::json::array({0, 0, w, d});
        room["purpose"] = "living";
        nlohmann::json story;
        story["height"] = 3;
        story["rooms"] = nlohmann::json::array({room});
        story["portals"] = nlohmann::json::array();
        story["stairs"] = nlohmann::json::array();
        if (s == 0)
            story["portals"].push_back({{"between", {"exterior", "r0"}},
                                        {"pos", {0, d / 2}}, {"width", 1}, {"height", 2}, {"kind", "door"}});
        if (withStairs && s < stories - 1) {
            nlohmann::json st;
            st["from_story"] = s; st["to_story"] = s + 1;
            st["rect"] = nlohmann::json::array({1, 2, 2, 6}); st["form"] = form;
            story["stairs"].push_back(st);
        }
        j["stories"].push_back(story);
    }
    return BuildingProgram::fromJson(j);
}

// A single-story two-room layout (hall + kitchen) tiling a 7x9 footprint, with the exterior door
// on the hall. `connected` adds the hall<->kitchen interior arch; when false the kitchen is SEALED.
BuildingProgram twoRoom(bool connected) {
    nlohmann::json j;
    j["name"] = "2room"; j["style"] = "timber_cottage";
    j["footprint"] = nlohmann::json::array({7, 9});
    j["substructure"] = "crawlspace"; j["roof_style"] = "gable";
    nlohmann::json hall, kitchen, story;
    hall["id"] = "hall"; hall["rect"] = nlohmann::json::array({0, 0, 4, 9}); hall["purpose"] = "living";
    kitchen["id"] = "kitchen"; kitchen["rect"] = nlohmann::json::array({4, 0, 3, 9}); kitchen["purpose"] = "kitchen";
    story["height"] = 3; story["rooms"] = nlohmann::json::array({hall, kitchen});
    story["portals"] = nlohmann::json::array();
    story["portals"].push_back({{"between", {"exterior", "hall"}}, {"pos", {0, 4}}, {"width", 1}, {"height", 2}, {"kind", "door"}});
    if (connected)
        story["portals"].push_back({{"between", {"hall", "kitchen"}}, {"pos", {4, 4}}, {"width", 1}, {"height", 2}, {"kind", "arch"}});
    story["stairs"] = nlohmann::json::array();
    j["stories"] = nlohmann::json::array({story});
    return BuildingProgram::fromJson(j);
}

// A 1-story building whose rooms are AUTO-GENERATED by generate_room_layout (placer #05) — no
// hand-authoring. Must pass the harness floors (L2) + rooms (L3) layers like any other building.
BuildingProgram generated(int W, int D, int targetRooms, unsigned seed, bool connectInterior = true) {
    RoomLayout rl = generateRoomLayout(W, D, targetRooms, seed);
    nlohmann::json j;
    j["name"] = "gen"; j["style"] = "timber_cottage";
    j["footprint"] = nlohmann::json::array({W, D});
    j["substructure"] = "crawlspace"; j["roof_style"] = "gable";
    nlohmann::json story;
    story["height"] = 3; story["rooms"] = nlohmann::json::array();
    story["portals"] = nlohmann::json::array(); story["stairs"] = nlohmann::json::array();
    j["stories"] = nlohmann::json::array({story});
    BuildingProgram p = BuildingProgram::fromJson(j);
    p.stories[0].rooms = rl.rooms;       // inject the generated partition + doors
    p.stories[0].portals = rl.portals;
    if (!connectInterior) {              // NEGATIVE CONTROL: keep only the exterior entrance ->
        std::vector<ProgPortal> ext;     // interior rooms become unreachable from the entrance room
        for (const auto& pt : p.stories[0].portals)
            if (pt.a == "exterior" || pt.b == "exterior") ext.push_back(pt);
        p.stories[0].portals = ext;
    }
    return p;
}

// L3 (interior): on every story, a character-box can physically walk from the entrance room to
// EVERY other room's centre through the carved doorways. A sealed room (no portal) => unreachable.
bool roomsReachable(const StructureRealizer::ShellResult& sh, const BuildingProgram& p) {
    for (size_t s = 0; s < p.stories.size() && s < sh.floorTopByStory.size(); ++s) {
        const auto& rooms = p.stories[s].rooms;
        if (rooms.size() <= 1) continue;                       // single room: trivially navigable
        const int floorY = sh.floorTopByStory[s];
        const int W = p.footprintW * 9, D = p.footprintD * 9;
        TraversalProbe probe([&](int x, int y, int z) { return sh.canvas.occupiedMicro(x, y, z); },
                             AgentBox{2, 16, 4});
        const auto& r0 = rooms[0].rect;
        const glm::ivec3 start((r0.x + r0.w / 2) * 9 + 4, floorY, (r0.z + r0.d / 2) * 9 + 4);
        const glm::ivec3 bLo(0, floorY - 2, 0), bHi(W, floorY + 28, D);
        for (size_t r = 1; r < rooms.size(); ++r) {
            const auto& rc = rooms[r].rect;
            const int gx = (rc.x + rc.w / 2) * 9 + 4, gz = (rc.z + rc.d / 2) * 9 + 4;
            if (!probe.reachable(start, glm::ivec3(gx - 2, floorY - 1, gz - 2),
                                 glm::ivec3(gx + 2, floorY + 1, gz + 2), bLo, bHi))
                return false;
        }
    }
    return true;
}

// L2: every room on every story has a floor cell at its centre (somewhere to stand).
bool floorsContinuous(const StructureRealizer::ShellResult& sh, const BuildingProgram& p) {
    for (size_t s = 0; s < p.stories.size() && s < sh.floorTopByStory.size(); ++s) {
        const int slabTop = sh.floorTopByStory[s] - 1;   // top micro of the floor slab
        for (const auto& room : p.stories[s].rooms) {
            const int cx = (room.rect.x + room.rect.w / 2) * 9 + 4;
            const int cz = (room.rect.z + room.rect.d / 2) * 9 + 4;
            if (!sh.canvas.occupiedMicro(cx, slabTop, cz)) return false;
        }
    }
    return true;
}

// L3: a character-box climbs from the ground floor to the TOP floor. Bounded to the (shared)
// stair well + a 1-cube margin. Multi-story with no stair => upper floors sealed => false.
bool topReachable(const StructureRealizer::ShellResult& sh, const BuildingProgram& p) {
    const int n = static_cast<int>(p.stories.size());
    if (n <= 1) return true;                          // single story: trivially "all floors"
    Rect well; bool haveWell = false;
    for (const auto& st : p.stories)
        for (const auto& s : st.stairs) { well = s.rect; haveWell = true; break; }
    if (!haveWell) return false;                      // no stairs in a multi-story building
    if ((int)sh.floorTopByStory.size() < n) return false;

    const int floor0 = sh.floorTopByStory[0];
    const int topY   = sh.floorTopByStory[n - 1];
    const int wx0 = well.x * 9, wz0 = well.z * 9, wxm = well.w * 9, wzm = well.d * 9;

    TraversalProbe probe([&](int x, int y, int z) { return sh.canvas.occupiedMicro(x, y, z); },
                         AgentBox{2, 16, 4});
    // Start inside LANE A (where a switchback's first flight runs), not the well centre (the lane
    // seam), and just south of the well so the agent walks in and climbs — matches the proven
    // AgentCanClimbSwitchbackToTopFloor start.
    const glm::ivec3 start(wx0 + wxm / 4, floor0, std::max(0, wz0 - 4));
    const glm::ivec3 goalLo(wx0 - 9, topY - 1, wz0 - 9), goalHi(wx0 + wxm + 9, topY + 2, wz0 + wzm + 9);
    const glm::ivec3 bLo(std::max(0, wx0 - 9), 0, std::max(0, wz0 - 9));
    const glm::ivec3 bHi(wx0 + wxm + 9, topY + 30, wz0 + wzm + 9);
    return probe.reachable(start, goalLo, goalHi, bLo, bHi);
}

struct CaseResult {
    std::string name;
    bool build = false, floors = false, reach = false, rooms = false;
    bool roomsTested = false;   // false => single-room everywhere => rooms check is N/A (not "ok")
    bool pass() const { return build && floors && reach && rooms; }
};

// True if any story has >1 room — i.e. the room-reachability check actually measures something.
bool hasMultiRoomStory(const BuildingProgram& p) {
    for (const auto& s : p.stories) if (s.rooms.size() > 1) return true;
    return false;
}

CaseResult runCase(const std::string& name, const BuildingProgram& p, const StyleProfile& style) {
    CaseResult r; r.name = name;
    auto sh = StructureRealizer::realizeShell(p, style);
    glm::ivec3 lo, hi;
    r.build = sh.ok && sh.canvas.microBounds(lo, hi);
    if (!r.build) return r;
    r.floors = floorsContinuous(sh, p);
    r.reach  = topReachable(sh, p);
    r.roomsTested = hasMultiRoomStory(p);
    r.rooms  = roomsReachable(sh, p);   // trivially true when not roomsTested
    return r;
}

}  // namespace

// The corpus run + matrix report. Asserts the harness has TEETH (a stairless multi-story is
// flagged unreachable) and that the canonical exemplar passes; everything else is reported so
// the real pass-rate is visible (the sign-off number).
TEST(BuildingHarness, Corpus) {
    const StyleProfile style = harnessStyle();
    struct Spec { std::string name; BuildingProgram p; };
    std::vector<Spec> corpus = {
        {"1-story 7x9",                 tower(1, 7, 9, "switchback", "crawlspace", true)},
        {"1-story 5x6 small",           tower(1, 5, 6, "switchback", "crawlspace", true)},
        {"1-story 12x14 large",         tower(1, 12, 14, "switchback", "crawlspace", true)},
        {"2-story switchback",          tower(2, 7, 9, "switchback", "crawlspace", true)},
        {"3-story switchback (exemplar)",tower(3, 7, 9, "switchback", "crawlspace", true)},
        {"5-story switchback",          tower(5, 7, 9, "switchback", "crawlspace", true)},
        {"10-story switchback",         tower(10, 7, 9, "switchback", "crawlspace", true)},
        {"3-story switchback slab",     tower(3, 7, 9, "switchback", "slab", true)},
        {"3-story switchback basement", tower(3, 7, 9, "switchback", "basement", true)},
        {"2-story straight",            tower(2, 7, 9, "straight", "crawlspace", true)},
        {"3-story straight",            tower(3, 7, 9, "straight", "crawlspace", true)},
        {"2-room connected",            twoRoom(true)},
        {"gen 7x9 rooms=3 seed1",       generated(7, 9, 3, 1)},
        {"gen 7x9 rooms=4 seed2",       generated(7, 9, 4, 2)},
        {"gen 10x12 rooms=5 seed3",     generated(10, 12, 5, 3)},
        {"gen 9x11 rooms=6 seed4",      generated(9, 11, 6, 4)},
        {"BAD: 3-story NO stairs",      tower(3, 7, 9, "switchback", "crawlspace", false)},
        {"BAD: 2-room sealed kitchen",  twoRoom(false)},
        {"BAD: gen doors stripped",     generated(9, 11, 6, 4, /*connectInterior=*/false)},
    };

    std::cout << "\n=== BUILDING VALIDATION HARNESS ===\n";
    std::cout << "case                              build  floors  reach  rooms  OVERALL\n";
    int passed = 0;
    CaseResult badStairs, badRooms, exemplar, twoRoomOk, genStripped, genOk;
    for (const auto& c : corpus) {
        CaseResult r = runCase(c.name, c.p, style);
        auto yn = [](bool b) { return b ? " ok " : "FAIL"; };
        const std::string roomsCol = r.build ? (r.roomsTested ? yn(r.rooms) : "n/a ") : "----";
        std::cout << "  " << c.name;
        for (int i = (int)c.name.size(); i < 32; ++i) std::cout << ' ';
        std::cout << "  " << yn(r.build) << "   " << yn(r.floors) << "   " << yn(r.reach)
                  << "   " << roomsCol << "   " << (r.pass() ? "PASS" : "----") << "\n";
        if (r.pass()) ++passed;
        if (c.name == "BAD: 3-story NO stairs") badStairs = r;
        if (c.name == "BAD: 2-room sealed kitchen") badRooms = r;
        if (c.name == "3-story switchback (exemplar)") exemplar = r;
        if (c.name == "2-room connected") twoRoomOk = r;
        if (c.name == "BAD: gen doors stripped") genStripped = r;
        if (c.name == "gen 9x11 rooms=6 seed4") genOk = r;
    }
    std::cout << "--- " << passed << " / " << corpus.size() << " cases pass ---\n\n";

    // Teeth: a stairless multi-story, a sealed room, AND a generated layout with its interior doors
    // stripped must all be flagged unreachable.
    EXPECT_FALSE(badStairs.reach)   << "no teeth: a stairless 3-story read as reachable";
    EXPECT_FALSE(badRooms.rooms)    << "no teeth: a sealed kitchen read as reachable";
    EXPECT_FALSE(genStripped.rooms) << "no teeth: a door-stripped generated layout read as navigable";
    // Regression guards: exemplar, a doored two-room cottage, and a GENERATED layout fully pass.
    EXPECT_TRUE(exemplar.pass())    << "the 3-story switchback exemplar regressed";
    EXPECT_TRUE(twoRoomOk.pass())   << "a connected two-room cottage is not fully navigable";
    EXPECT_TRUE(genOk.pass())       << "an auto-generated room layout is not fully navigable";
}
