// Tavern signage — the sign is a fine-voxel ITEM, not a blank furniture board.
//
// The generated tavern used to hang `hanging_sign` (furniture/hanging_sign.voxel):
// a bracket + a BLANK painted board. It cannot say anything, so a generated
// tavern was nameless. resources/templates/items/sign_prancing_pony.voxel is a
// fine-grid item carrying a real projected sign image — that is what a tavern
// should hang.
//
// Two things are pinned here:
//  1. The sign asset is DATA on the typology (room_program.json "sign_item"),
//     not a name hard-coded in the forge. A business typology without one falls
//     back to the blank board and records an asset request — it never invents.
//  2. The MOUNT is chosen by fit against the grounded projecting-sign code
//     (>= 8 ft clearance, <= 48 in projection, above the door head). A board too
//     wide to hang on a bracket within that cap mounts FLUSH to the facade
//     instead of being silently skipped — repair-then-refuse, same as every
//     other forge gate.

#include <gtest/gtest.h>

#include <filesystem>

#include "core/ItemRegistry.h"
#include "core/RoomProgram.h"
#include "core/StructureForge.h"

namespace fs = std::filesystem;
using namespace Phyxel;
using namespace Phyxel::Core;

namespace {

bool loadCanon(RoomProgramRegistry& reg) {
    for (const char* p : {"resources/room_program.json", "../resources/room_program.json",
                          "../../resources/room_program.json",
                          "../../../resources/room_program.json"})
        if (reg.loadFromFile(p)) return true;
    return false;
}

// The Prancing Pony board as generated by tools/gen_items.py: 54 x 40 x 1 cells
// on a 27-cell grid = 2.000 x 1.481 x 0.037 u.
constexpr float kPonyW = 54.0f / 27.0f;
constexpr float kPonyH = 40.0f / 27.0f;
constexpr float kPonyT = 1.0f / 27.0f;

}  // namespace

// ---------------------------------------------------------------------------
// 1. The asset is data on the typology.
// ---------------------------------------------------------------------------

TEST(SignMount, TavernDeclaresItsSignAsset) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    const RoomProgram* tavern = reg.get("tavern");
    ASSERT_NE(tavern, nullptr);
    EXPECT_EQ(tavern->signItem, "prop_sign_prancing_pony")
        << "the tavern must name its sign asset in room_program.json — the forge "
           "must not hard-code which sign a typology hangs";
}

TEST(SignMount, TheDeclaredSignIsARealHoldableItem) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    const RoomProgram* tavern = reg.get("tavern");
    ASSERT_NE(tavern, nullptr);
    ASSERT_FALSE(tavern->signItem.empty());

    ItemRegistry::instance().loadFromFile("resources/items.json");
    const auto* def = ItemRegistry::instance().getItem(tavern->signItem);
    ASSERT_NE(def, nullptr) << tavern->signItem << " is not a registered item";
    EXPECT_TRUE(def->holdable) << "spawnProp refuses non-holdable items";
    ASSERT_FALSE(def->templateFile.empty());
    EXPECT_TRUE(fs::exists("resources/templates/" + def->templateFile))
        << def->templateFile << " missing on disk";
}

// Every declared sign_item must resolve to a REAL registered, holdable item with a
// template on disk — never a borrowed or invented name (the substitution the pipeline
// exists to prevent). Since 2026-08-27 all five trades own authored default boards
// (gen_trade_signs.py); residential typologies still declare nothing.
TEST(SignMount, EveryDeclaredSignAssetResolvesAndHomesStayBlank) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    ItemRegistry::instance().loadFromFile("resources/items.json");
    for (const char* name : {"blacksmith", "bakery", "apothecary", "butcher",
                             "general_store"}) {
        const RoomProgram* p = reg.get(name);
        if (!p) continue;
        ASSERT_FALSE(p->signItem.empty())
            << name << " lost its authored default trade sign";
        const auto* def = ItemRegistry::instance().getItem(p->signItem);
        ASSERT_NE(def, nullptr) << name << " declares unregistered sign '" << p->signItem << "'";
        EXPECT_TRUE(def->holdable) << "spawnProp refuses non-holdable items";
        ASSERT_FALSE(def->templateFile.empty());
        EXPECT_TRUE(fs::exists("resources/templates/" + def->templateFile))
            << def->templateFile << " missing on disk";
    }
    for (const char* name : {"croft", "longhouse", "hall_house", "manor_hall"}) {
        const RoomProgram* p = reg.get(name);
        if (!p) continue;
        EXPECT_TRUE(p->signItem.empty()) << name << " is not a trade; no sign";
    }
}

// ---------------------------------------------------------------------------
// 2. Mount selection by fit.
// ---------------------------------------------------------------------------

// floor at micro-Y 0; a 3-cube door => head at 27; no roof constraint.
constexpr int kFloor = 0, kDoorHead = 27, kNoApex = 0;

TEST(SignMount, ASmallBoardHangsOnAProjectingBracket) {
    // 0.9 u wide = 9 micro, well inside the 19-micro (7 ft) projection cap.
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, /*wallOuterMicro=*/360,
        /*alongCenterMicro=*/400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/0.9f, /*boardH=*/0.7f, /*boardT=*/kPonyT);
    ASSERT_TRUE(m.ok) << m.skipReason;
    EXPECT_EQ(m.form, "projecting")
        << "a board within the projection cap must hang on a bracket — the "
           "authentic medieval trade-sign form";
    // Board local +X points along the outward normal (-X) => yaw 180.
    EXPECT_EQ(m.rotationDeg, 180);
    // It juts OUT from the wall: center half a board-width outside the face.
    EXPECT_NEAR(m.worldPos.x, 360.0f / 9.0f - 0.45f, 0.02f);
    EXPECT_NEAR(m.worldPos.z, 400.0f / 9.0f, 1e-3f);
}

// An inn sign HANGS OUT over the road — that is the entire point of an alestake.
// The Pony board projects 18 micro (2.0 m), inside the 19-micro / 7 ft medieval
// ordinance limit, so it must swing on a bracket, not lie flat on the facade.
TEST(SignMount, ThePonyBoardHangsOutFrontNotFlatOnTheWall) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        kPonyW, kPonyH, kPonyT);
    ASSERT_TRUE(m.ok) << m.skipReason;
    EXPECT_EQ(m.form, "projecting")
        << "the sign is flat against the wall — a tavern sign must project over "
           "the road so it reads from along it (1375 London ale-stake ordinance "
           "allows 7 ft of projection; this board needs 6.6 ft)";
    // Board local +X points along the outward normal (-X) => yaw 180.
    EXPECT_EQ(m.rotationDeg, 180);
    // It juts OUT: centre sits a half-board-width clear of the wall face.
    EXPECT_NEAR(m.worldPos.x, 360.0f / 9.0f - kPonyW * 0.5f, 0.02f);
    EXPECT_GT(m.projectionMicro, 11) << "this is the case the modern 48-in cap wrongly rejected";
    EXPECT_LE(m.projectionMicro, 19);
}

// A board too big even for the medieval ordinance still falls back to flush
// rather than vanishing — repair-then-refuse, not skip.
TEST(SignMount, AnOverlongBoardFallsBackToFlushInsteadOfBeingSkipped) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/3.5f, kPonyH, kPonyT);
    ASSERT_TRUE(m.ok) << "an over-long board vanished instead of mounting flush: "
                      << m.skipReason;
    EXPECT_EQ(m.form, "flush");
    EXPECT_EQ(m.rotationDeg, 270);
    EXPECT_LE(m.projectionMicro, 19);
}

TEST(SignMount, MountsRespectClearanceAndTheDoorHead) {
    for (auto side : {StructureForge::WallSide::MinusX, StructureForge::WallSide::PlusX,
                      StructureForge::WallSide::MinusZ, StructureForge::WallSide::PlusZ}) {
        const auto m = StructureForge::planSignMount(side, 360, 400, kFloor,
                                                     kDoorHead, kNoApex,
                                                     kPonyW, kPonyH, kPonyT);
        ASSERT_TRUE(m.ok) << m.skipReason;
        EXPECT_GE(m.boardBottomMicroY - kFloor, 22)
            << "board bottom must clear 8 ft of grade";
        EXPECT_GT(m.boardBottomMicroY, kDoorHead)
            << "the sign must crown the doorway, not obscure it";
        EXPECT_NEAR(m.worldPos.y, m.boardBottomMicroY / 9.0f, 1e-4f)
            << "spawnProp rests a static prop ON pos.y — that must be the board bottom";
    }
}

// A roof too low to clear both the lintel and the 8 ft rule refuses honestly
// rather than burying the sign in the eave.
TEST(SignMount, ARoofTooLowToClearRefuses) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead,
        /*roofApexMicroY=*/30, kPonyW, kPonyH, kPonyT);
    EXPECT_FALSE(m.ok);
    EXPECT_FALSE(m.skipReason.empty());
}

// Each wall's board must end up OUTSIDE the shell, never buried in the wall.
TEST(SignMount, EveryWallPutsTheBoardOutside) {
    struct Case { StructureForge::WallSide side; float sign; bool onX; };
    const Case cases[] = {
        {StructureForge::WallSide::MinusX, -1.0f, true},
        {StructureForge::WallSide::PlusX,  +1.0f, true},
        {StructureForge::WallSide::MinusZ, -1.0f, false},
        {StructureForge::WallSide::PlusZ,  +1.0f, false},
    };
    const float face = 360.0f / 9.0f;
    for (const auto& c : cases) {
        // Use the small board so the projecting form is selected — that is the
        // case where an inward sign error would be most visible.
        const auto m = StructureForge::planSignMount(c.side, 360, 400, kFloor,
                                                     kDoorHead, kNoApex,
                                                     0.9f, 0.7f, kPonyT);
        ASSERT_TRUE(m.ok) << m.skipReason;
        const float along = c.onX ? m.worldPos.x : m.worldPos.z;
        EXPECT_GT((along - face) * c.sign, 0.0f)
            << "board center is on the INSIDE of the wall face";
    }
}

// ---------------------------------------------------------------------------
// 3. SignMount v2 (user feedback 2026-08-27): a projecting sign HANGS from a
//    real bracket, a blocked projection repairs to flush, a blocked flush
//    repairs to BESIDE the door, and the final pose never intersects the world.
//    RED baseline: bracketCells empty; no probe-driven repairs exist.
// ---------------------------------------------------------------------------

TEST(SignMount, AProjectingSignHangsFromARealBracket) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/1.48f, /*boardH=*/1.48f, /*boardT=*/kPonyT);
    ASSERT_TRUE(m.ok) << m.skipReason;
    ASSERT_EQ(m.form, "projecting");
    ASSERT_FALSE(m.bracketCells.empty()) << "a projecting board floats in the air; "
                                            "it must hang from a wrought-iron bracket";
    const int boardTop = m.boardBottomMicroY + 14;   // 1.48 u = 14 micro (ceil)
    bool touchesWall = false, reachesBoard = false;
    for (const auto& c : m.bracketCells) {
        EXPECT_GE(c.y, boardTop) << "bracket cell inside the board body";
        // -X wall, outer face micro 360: the bracket lives OUTSIDE the face (x <= 360),
        // anchored INTO its outermost micro column.
        EXPECT_LE(c.x, 360);
        if (c.x >= 359) touchesWall = true;
        if (c.x <= 360 - m.projectionMicro / 2) reachesBoard = true;
    }
    EXPECT_TRUE(touchesWall) << "the bracket arm never anchors into the wall";
    EXPECT_TRUE(reachesBoard) << "the bracket arm stops short of the board it hangs";
}

TEST(SignMount, ABlockedProjectionRepairsToFlush) {
    // A fake EAVE: everything outside the wall face at y >= 30 is solid; the wall
    // plane itself (and the beside-door band under the eave) stays clear.
    auto solid = [](const glm::ivec3& c) { return c.x < 360 && c.y >= 30; };
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/1.48f, /*boardH=*/1.48f, /*boardT=*/kPonyT, solid);
    ASSERT_TRUE(m.ok) << "a blocked projection must REPAIR, not vanish: " << m.skipReason;
    EXPECT_EQ(m.form, "flush") << "board+bracket intersect the eave; flush is the repair";
}

TEST(SignMount, ABlockedFlushMountGoesBesideTheDoor) {
    // Solid over the door span above the head (a low jetty), clear elsewhere.
    auto solid = [](const glm::ivec3& c) {
        return c.x < 360 && c.y > kDoorHead && c.z >= 395 && c.z <= 405;
    };
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/1.48f, /*boardH=*/1.48f, /*boardT=*/kPonyT, solid,
        /*doorWidthMicro=*/9);
    ASSERT_TRUE(m.ok) << "blocked above the door must repair BESIDE it: " << m.skipReason;
    EXPECT_EQ(m.form, "flush");
    // Beside = shifted along the wall clear of the door reveal, sitting at door height.
    EXPECT_GE(std::abs(m.worldPos.z - 400.0f / 9.0f), (9 / 2 + 14 / 2) / 9.0f - 0.01f)
        << "the beside pose still overlaps the door span";
    EXPECT_LE(m.boardBottomMicroY, kDoorHead) << "beside-the-door boards sit at door height";
}

TEST(SignMount, TheChosenPoseNeverIntersectsTheWorld) {
    // Probe that records consultation and reports a solid eave slab.
    std::vector<glm::ivec3> asked;
    auto solid = [&asked](const glm::ivec3& c) {
        asked.push_back(c);
        return c.x < 360 && c.y >= 30;
    };
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/1.48f, /*boardH=*/1.48f, /*boardT=*/kPonyT, solid);
    ASSERT_TRUE(m.ok) << m.skipReason;
    ASSERT_FALSE(asked.empty()) << "a probe was supplied but never consulted";
    // Self-check the FINAL pose against the same slab: board box must be all air.
    const int bh = 14, bt = 2;
    const float wx = m.worldPos.x * 9.0f, wz = m.worldPos.z * 9.0f;
    for (int y = m.boardBottomMicroY; y < m.boardBottomMicroY + bh; ++y)
        for (int dz = -bt / 2; dz <= bt / 2; ++dz) {
            const glm::ivec3 c((int)std::floor(wx), y, (int)std::floor(wz) + dz);
            EXPECT_FALSE(c.x < 360 && c.y >= 30)
                << "final pose intersects the solid eave at y=" << y;
        }
    for (const auto& c : m.bracketCells)
        EXPECT_FALSE(c.x < 360 && c.y >= 30) << "bracket intersects the eave";
}
