// Tavern signage — the sign is a fine-voxel ITEM, not a blank furniture board.
//
// The generated tavern used to hang `hanging_sign` (furniture/hanging_sign.voxel):
// a bracket + a BLANK painted board. It cannot say anything, so a generated
// tavern was nameless. resources/templates/items/sign_prancing_pony.voxel is a
// fine-grid item carrying a real projected sign image — that is what a tavern
// should hang.
//
// Two things are pinned here:
//  1. The sign asset is DATA on the typology (room_program.json "sign_item"),
//     not a name hard-coded in the forge. A business typology without one falls
//     back to the blank board and records an asset request — it never invents.
//  2. The MOUNT is chosen by fit against the grounded projecting-sign code
//     (>= 8 ft clearance, <= 48 in projection, above the door head). A board too
//     wide to hang on a bracket within that cap mounts FLUSH to the facade
//     instead of being silently skipped — repair-then-refuse, same as every
//     other forge gate.

#include <gtest/gtest.h>

#include <filesystem>

#include "core/ItemRegistry.h"
#include "core/RoomProgram.h"
#include "core/StructureForge.h"

namespace fs = std::filesystem;
using namespace Phyxel;
using namespace Phyxel::Core;

namespace {

bool loadCanon(RoomProgramRegistry& reg) {
    for (const char* p : {"resources/room_program.json", "../resources/room_program.json",
                          "../../resources/room_program.json",
                          "../../../resources/room_program.json"})
        if (reg.loadFromFile(p)) return true;
    return false;
}

// The Prancing Pony board as generated by tools/gen_items.py: 54 x 40 x 1 cells
// on a 27-cell grid = 2.000 x 1.481 x 0.037 u.
constexpr float kPonyW = 54.0f / 27.0f;
constexpr float kPonyH = 40.0f / 27.0f;
constexpr float kPonyT = 1.0f / 27.0f;

}  // namespace

// ---------------------------------------------------------------------------
// 1. The asset is data on the typology.
// ---------------------------------------------------------------------------

TEST(SignMount, TavernDeclaresItsSignAsset) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    const RoomProgram* tavern = reg.get("tavern");
    ASSERT_NE(tavern, nullptr);
    EXPECT_EQ(tavern->signItem, "prop_sign_prancing_pony")
        << "the tavern must name its sign asset in room_program.json — the forge "
           "must not hard-code which sign a typology hangs";
}

TEST(SignMount, TheDeclaredSignIsARealHoldableItem) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    const RoomProgram* tavern = reg.get("tavern");
    ASSERT_NE(tavern, nullptr);
    ASSERT_FALSE(tavern->signItem.empty());

    ItemRegistry::instance().loadFromFile("resources/items.json");
    const auto* def = ItemRegistry::instance().getItem(tavern->signItem);
    ASSERT_NE(def, nullptr) << tavern->signItem << " is not a registered item";
    EXPECT_TRUE(def->holdable) << "spawnProp refuses non-holdable items";
    ASSERT_FALSE(def->templateFile.empty());
    EXPECT_TRUE(fs::exists("resources/templates/" + def->templateFile))
        << def->templateFile << " missing on disk";
}

// A business typology with no authored sign must NOT silently borrow the
// tavern's — that is exactly the substitution the pipeline exists to prevent.
TEST(SignMount, TypologiesWithoutASignAssetDeclareNothing) {
    RoomProgramRegistry reg;
    ASSERT_TRUE(loadCanon(reg));
    for (const char* name : {"blacksmith", "bakery", "apothecary", "butcher",
                             "general_store"}) {
        const RoomProgram* p = reg.get(name);
        if (!p) continue;
        EXPECT_TRUE(p->signItem.empty())
            << name << " claims sign asset '" << p->signItem
            << "' — no such asset was authored; it must stay empty so the build "
               "records an asset request instead of hanging the wrong sign";
    }
}

// ---------------------------------------------------------------------------
// 2. Mount selection by fit.
// ---------------------------------------------------------------------------

// floor at micro-Y 0; a 3-cube door => head at 27; no roof constraint.
constexpr int kFloor = 0, kDoorHead = 27, kNoApex = 0;

TEST(SignMount, ASmallBoardHangsOnAProjectingBracket) {
    // 0.9 u wide = 9 micro, well inside the 19-micro (7 ft) projection cap.
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, /*wallOuterMicro=*/360,
        /*alongCenterMicro=*/400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/0.9f, /*boardH=*/0.7f, /*boardT=*/kPonyT);
    ASSERT_TRUE(m.ok) << m.skipReason;
    EXPECT_EQ(m.form, "projecting")
        << "a board within the projection cap must hang on a bracket — the "
           "authentic medieval trade-sign form";
    // Board local +X points along the outward normal (-X) => yaw 180.
    EXPECT_EQ(m.rotationDeg, 180);
    // It juts OUT from the wall: center half a board-width outside the face.
    EXPECT_NEAR(m.worldPos.x, 360.0f / 9.0f - 0.45f, 0.02f);
    EXPECT_NEAR(m.worldPos.z, 400.0f / 9.0f, 1e-3f);
}

// An inn sign HANGS OUT over the road — that is the entire point of an alestake.
// The Pony board projects 18 micro (2.0 m), inside the 19-micro / 7 ft medieval
// ordinance limit, so it must swing on a bracket, not lie flat on the facade.
TEST(SignMount, ThePonyBoardHangsOutFrontNotFlatOnTheWall) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        kPonyW, kPonyH, kPonyT);
    ASSERT_TRUE(m.ok) << m.skipReason;
    EXPECT_EQ(m.form, "projecting")
        << "the sign is flat against the wall — a tavern sign must project over "
           "the road so it reads from along it (1375 London ale-stake ordinance "
           "allows 7 ft of projection; this board needs 6.6 ft)";
    // Board local +X points along the outward normal (-X) => yaw 180.
    EXPECT_EQ(m.rotationDeg, 180);
    // It juts OUT: centre sits a half-board-width clear of the wall face.
    EXPECT_NEAR(m.worldPos.x, 360.0f / 9.0f - kPonyW * 0.5f, 0.02f);
    EXPECT_GT(m.projectionMicro, 11) << "this is the case the modern 48-in cap wrongly rejected";
    EXPECT_LE(m.projectionMicro, 19);
}

// A board too big even for the medieval ordinance still falls back to flush
// rather than vanishing — repair-then-refuse, not skip.
TEST(SignMount, AnOverlongBoardFallsBackToFlushInsteadOfBeingSkipped) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead, kNoApex,
        /*boardW=*/3.5f, kPonyH, kPonyT);
    ASSERT_TRUE(m.ok) << "an over-long board vanished instead of mounting flush: "
                      << m.skipReason;
    EXPECT_EQ(m.form, "flush");
    EXPECT_EQ(m.rotationDeg, 270);
    EXPECT_LE(m.projectionMicro, 19);
}

TEST(SignMount, MountsRespectClearanceAndTheDoorHead) {
    for (auto side : {StructureForge::WallSide::MinusX, StructureForge::WallSide::PlusX,
                      StructureForge::WallSide::MinusZ, StructureForge::WallSide::PlusZ}) {
        const auto m = StructureForge::planSignMount(side, 360, 400, kFloor,
                                                     kDoorHead, kNoApex,
                                                     kPonyW, kPonyH, kPonyT);
        ASSERT_TRUE(m.ok) << m.skipReason;
        EXPECT_GE(m.boardBottomMicroY - kFloor, 22)
            << "board bottom must clear 8 ft of grade";
        EXPECT_GT(m.boardBottomMicroY, kDoorHead)
            << "the sign must crown the doorway, not obscure it";
        EXPECT_NEAR(m.worldPos.y, m.boardBottomMicroY / 9.0f, 1e-4f)
            << "spawnProp rests a static prop ON pos.y — that must be the board bottom";
    }
}

// A roof too low to clear both the lintel and the 8 ft rule refuses honestly
// rather than burying the sign in the eave.
TEST(SignMount, ARoofTooLowToClearRefuses) {
    const auto m = StructureForge::planSignMount(
        StructureForge::WallSide::MinusX, 360, 400, kFloor, kDoorHead,
        /*roofApexMicroY=*/30, kPonyW, kPonyH, kPonyT);
    EXPECT_FALSE(m.ok);
    EXPECT_FALSE(m.skipReason.empty());
}

// Each wall's board must end up OUTSIDE the shell, never buried in the wall.
TEST(SignMount, EveryWallPutsTheBoardOutside) {
    struct Case { StructureForge::WallSide side; float sign; bool onX; };
    const Case cases[] = {
        {StructureForge::WallSide::MinusX, -1.0f, true},
        {StructureForge::WallSide::PlusX,  +1.0f, true},
        {StructureForge::WallSide::MinusZ, -1.0f, false},
        {StructureForge::WallSide::PlusZ,  +1.0f, false},
    };
    const float face = 360.0f / 9.0f;
    for (const auto& c : cases) {
        // Use the small board so the projecting form is selected — that is the
        // case where an inward sign error would be most visible.
        const auto m = StructureForge::planSignMount(c.side, 360, 400, kFloor,
                                                     kDoorHead, kNoApex,
                                                     0.9f, 0.7f, kPonyT);
        ASSERT_TRUE(m.ok) << m.skipReason;
        const float along = c.onX ? m.worldPos.x : m.worldPos.z;
        EXPECT_GT((along - face) * c.sign, 0.0f)
            << "board center is on the INSIDE of the wall face";
    }
}
