"""Loop step 4: regenerate the Ravenmere town from a PRISTINE scene DB with the same recipe
(engine generator, seed 7). Run with the editor ALREADY launched on the project AFTER
worlds/town.db(-wal/-shm) were deleted. Prints the job result and a duplicate check."""
import json, time, urllib.request, urllib.parse, sys, collections, re
B='http://localhost:8090'
def call(method, path, body=None, t=120):
    req=urllib.request.Request(B+path, data=json.dumps(body).encode() if body is not None else None, method=method, headers={'Content-Type':'application/json'})
    return json.load(urllib.request.urlopen(req, timeout=t))
def get(path, **q): return call('GET', path+('?'+urllib.parse.urlencode(q) if q else ''))
for i in range(180):
    try: call('GET','/api/state'); break
    except Exception: time.sleep(1)
else: sys.exit('editor never answered')
print('transition:', call('POST','/api/scene/transition',{'scene_id':'town'}))
for i in range(90):
    a=call('GET','/api/scene/active')
    if a.get('id')=='town' and not a.get('transitioning'): break
    time.sleep(1)
time.sleep(5)
objs=call('GET','/api/placed_objects')['objects']; print('placed objects in the fresh scene:', len(objs))
# 1. flat terrain: same span as the original bake (surface at y=16), chunks x -2..1, y 0, z -1..1
print('terrain: generated by the TEMPORARY inline world block (Flat seed 7, chunks x-2..1 z-1..1); state =', str(call('GET','/api/state'))[:200])
time.sleep(3)
# 2. the settlement, same recipe as 2026-09-08
r=call('POST','/api/settlement/build',{'era':'medieval','tier':'town','seed':7,'position':{'x':-40,'y':16,'z':-20},'width':100,'depth':70}, t=300)
print('settlement/build:', json.dumps(r)[:300])
job=r.get('job_id') or r.get('jobId') or r.get('id')
t0=time.time()
while time.time()-t0 < 900:
    jobs=get('/api/jobs'); js=jobs if isinstance(jobs,list) else jobs.get('jobs',[])
    mine=[j for j in js if str(j.get('id'))==str(job)] if job else js
    running=[j for j in js if j.get('status') in ('running','queued','pending')]
    if mine and mine[0].get('status') not in ('running','queued','pending'):
        print('job done:', json.dumps(mine[0])[:600]); break
    if not running and time.time()-t0 > 20:
        print('no running jobs; last:', json.dumps(js[-1:] )[:400]); break
    time.sleep(10)
time.sleep(5)
print('save:', call('POST','/api/world/save',{'all':True}, t=120))
objs=call('GET','/api/placed_objects')['objects']
key=collections.Counter((re.sub(r'_\d+$','',o['id']),o['position']['x'],o['position']['y'],o['position']['z']) for o in objs)
dups=[k for k,c in key.items() if c>1]
print('placed objects:', len(objs), 'duplicate groups:', len(dups))
print('houses:', sorted(o['id'] for o in objs if o['id'].startswith('house_')))
