// GENERATED by tools/gen_grass_site_order.py — DO NOT EDIT BY HAND.
//
// Progressive blue-noise ordering of a 16x16 toroidal lattice (256 sites, pitch 0.0625 u).
// Blade `i` of a voxel occupies cell grassSiteOrder(i); one blade per cell, so blades cannot
// share a position and the grid tiles across voxel AND chunk borders with no special casing.
//
// EVERY PREFIX is well-spread, which is what lets the LOD thin the field by simply drawing fewer
// blades: survivors keep their cells, and the distribution stays even at any count.
//
//   MEASURED Cseq = 0.7099   (min over N of minSep(prefix N) * sqrt(N))
//
// Use the CONTINUOUS envelope Cseq/sqrt(N) for any spacing guarantee, never the per-N staircase —
// adjacent voxels can keep different N, and the staircase lets the sparser one assume a separation
// its neighbour does not honour.
#ifndef GRASS_SITES_GLSL
#define GRASS_SITES_GLSL

const uint  kGrassGrid       = 16u;
const float kGrassPitch      = 0.0625;
const float kGrassSeqSep     = 0.7099;   // Cseq

// 256 site indices packed 4-per-uint, 4 uints per uvec4.
const uvec4 kGrassSiteWords[16] = uvec4[16](
    uvec4(0x80088800u, 0xccc44c44u, 0x48400c04u, 0xc8c08c84u),
    uvec4(0x2e2a2622u, 0x6e6a6662u, 0xaeaaa6a2u, 0xeeeae6e2u),
    uvec4(0x0e0a0602u, 0x2c282420u, 0x4e4a4642u, 0x6c686460u),
    uvec4(0x8e8a8682u, 0xaca8a4a0u, 0xcecac6c2u, 0xece8e4e0u),
    uvec4(0x17151311u, 0x1f1d1b19u, 0x37353331u, 0x3f3d3b39u),
    uvec4(0x57555351u, 0x5f5d5b59u, 0x77757371u, 0x7f7d7b79u),
    uvec4(0x97959391u, 0x9f9d9b99u, 0xb7b5b3b1u, 0xbfbdbbb9u),
    uvec4(0xd7d5d3d1u, 0xdfdddbd9u, 0xf7f5f3f1u, 0xfffdfbf9u),
    uvec4(0x07050301u, 0x0f0d0b09u, 0x16141210u, 0x1e1c1a18u),
    uvec4(0x27252321u, 0x2f2d2b29u, 0x36343230u, 0x3e3c3a38u),
    uvec4(0x47454341u, 0x4f4d4b49u, 0x56545250u, 0x5e5c5a58u),
    uvec4(0x67656361u, 0x6f6d6b69u, 0x76747270u, 0x7e7c7a78u),
    uvec4(0x87858381u, 0x8f8d8b89u, 0x96949290u, 0x9e9c9a98u),
    uvec4(0xa7a5a3a1u, 0xafadaba9u, 0xb6b4b2b0u, 0xbebcbab8u),
    uvec4(0xc7c5c3c1u, 0xcfcdcbc9u, 0xd6d4d2d0u, 0xdedcdad8u),
    uvec4(0xe7e5e3e1u, 0xefedebe9u, 0xf6f4f2f0u, 0xfefcfaf8u)
);

// Cell index for blade `i` (i must be < 256).
uint grassSiteOrder(uint i) {
    uint w    = i >> 2u;                              // which packed uint (0..63)
    uint word = kGrassSiteWords[w >> 2u][w & 3u];
    return (word >> ((i & 3u) * 8u)) & 0xFFu;
}

// Lattice-cell centre, in [0,1]^2 voxel-local space, for blade `i`.
vec2 grassSiteCentre(uint i) {
    uint s = grassSiteOrder(i);
    return (vec2(float(s & (kGrassGrid - 1u)), float(s >> 4u)) + 0.5) * kGrassPitch;
}

#endif // GRASS_SITES_GLSL
