#!/usr/bin/env python3
"""Generate a human-readable DIMENSION REFERENCE doc from the grounded canon.

The canon JSON (resources/object_dimensions.json + room_program.json) is the SOURCE OF TRUTH —
this doc is GENERATED from it so it can never drift. Re-run after editing the canon:

    python tools/gen_dimension_doc.py

Writes docs/structure-generation/DimensionReference.md.
"""
import json
import os
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OBJ = os.path.join(ROOT, "resources", "object_dimensions.json")
ROOMS = os.path.join(ROOT, "resources", "room_program.json")
OUT = os.path.join(ROOT, "docs", "structure-generation", "DimensionReference.md")

# dimension keys to surface as the "size" column (everything else that's numeric is shown too)
SIZE_KEYS = ["height", "width", "depth", "length", "diameter", "top", "seat_top", "mount_height",
             "hang_height", "post_spacing", "bay_length", "proportion_max"]


def fmt_dims(rec):
    parts = []
    for k, v in rec.items():
        if isinstance(v, (int, float)) and k not in ("tol",):
            parts.append(f"{k} {v}")
    tol = rec.get("tol")
    s = ", ".join(parts)
    if tol is not None:
        s += f"  (±{tol})"
    return s or "—"


def fmt_sources(rec):
    src = rec.get("sources", {})
    lines = []
    if rec.get("source"):
        lines.append(f"**source:** {rec['source']}")
    for k, v in src.items():
        lines.append(f"`{k}`: {v}")
    return "<br>".join(lines) if lines else "_(unsourced)_"


def main():
    obj = json.load(open(OBJ, encoding="utf-8")).get("archetypes", {})
    rooms = json.load(open(ROOMS, encoding="utf-8")).get("programs", {})

    # group object archetypes by category
    by_cat = {}
    for name, rec in obj.items():
        if name.startswith("_"):
            continue
        by_cat.setdefault(rec.get("category", "other"), []).append((name, rec))

    L = []
    L.append("<!-- GENERATED by tools/gen_dimension_doc.py from resources/object_dimensions.json +")
    L.append("     resources/room_program.json. DO NOT EDIT BY HAND — edit the canon JSON + regenerate. -->")
    L.append("")
    L.append("# Dimension Reference (grounded canon)")
    L.append("")
    L.append(f"_Generated {date.today().isoformat()} from `resources/object_dimensions.json` + "
             "`resources/room_program.json` — the engine's source of truth. Every value carries its "
             "citation. Units = metres (1 voxel cube = 1 m; microcube grid = 1/9 m ≈ 0.111 m). "
             "Regenerate with `python tools/gen_dimension_doc.py`._")
    L.append("")
    L.append(f"**{sum(len(v) for v in by_cat.values())} object archetypes** across "
             f"{len(by_cat)} categories · **{len([k for k in rooms if not k.startswith('_')])} "
             "building typologies**.")
    L.append("")

    for cat in sorted(by_cat):
        L.append(f"## {cat.capitalize()}")
        L.append("")
        L.append("| archetype | dimensions (m) | grounding / sources |")
        L.append("|---|---|---|")
        for name, rec in sorted(by_cat[cat]):
            L.append(f"| **{name}** | {fmt_dims(rec)} | {fmt_sources(rec)} |")
        L.append("")

    L.append("## Building typologies (room programs)")
    L.append("")
    L.append("Bay-driven medieval frames. `bays` = structural-bay count; rooms allocate bays.")
    L.append("")
    L.append("| typology | frame (m) | rooms | grounding / sources |")
    L.append("|---|---|---|---|")
    for name, rec in sorted(rooms.items()):
        if name.startswith("_"):
            continue
        frame = (f"width {rec.get('width_min','?')}-{rec.get('width_max','?')}, "
                 f"bay {rec.get('bay_length','?')}, {rec.get('bays','?')} bays"
                 + (f", {rec['stories']} stories" if rec.get("stories", 1) > 1 else ""))
        rooms_s = ", ".join(f"{r.get('id','?')}({r.get('purpose','?')},{r.get('bays','?')}b)"
                            for r in rec.get("rooms", []))
        L.append(f"| **{name}** | {frame} | {rooms_s} | {fmt_sources(rec)} |")
    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {OUT}  ({sum(len(v) for v in by_cat.values())} archetypes, "
          f"{len([k for k in rooms if not k.startswith('_')])} typologies)")


if __name__ == "__main__":
    main()
