#!/usr/bin/env python3
"""gen_spell_icons.py - one pixel-art icon per spell, plus the non-spell action-bar actions.

WHY GENERATED. The spell list is data (resources/spells/*.json) and it grows; a hand-painted
icon set goes stale the moment a spell is added. This reads the same JSON the engine loads,
so every spell it knows about gets an icon, and an unknown spell still resolves to its
school's fallback instead of a blank slot.

SIZE. Drawn on a 16x16 grid, scaled 4x nearest-neighbour to 64x64 px - the chunky pixel look
that matches the voxel aesthetic, and the size the source art is authored at. The HUD draws
them at 44 px inside a 52 px action-bar slot, which follows the shipped hotbar's own
proportions (a 46 px icon inside a 62 px slot, resources/ui/default_hud.json).

COLOUR is data-driven, not decoration: damage type first (a Fire spell is orange, a Necrotic
one sickly green), then healing, then school. Two spells never share both a glyph and a
palette.

  python tools/gen_spell_icons.py            # write resources/ui/icons/spells/*.png
  python tools/gen_spell_icons.py --sheet    # also write a contact sheet to review the set
  python tools/gen_spell_icons.py --check    # fail if any spell has no icon file
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

from PIL import Image, ImageDraw

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPELL_DIR = os.path.join(REPO, "resources", "spells")
OUT_DIR = os.path.join(REPO, "resources", "ui", "icons", "spells")

CELL = 16          # glyph grid
SCALE = 4          # -> 64x64 px
SIZE = CELL * SCALE

# -- Palettes ---------------------------------------------------------------
# (main, light, accent, badge) - badge is the dark plate the glyph sits on so an
# icon stays readable against any HUD background.
PAL = {
    "fire":      ((222,  82,  28), (255, 186,  84), (255, 238, 176), ( 46,  18,  10)),
    "cold":      (( 96, 170, 224), (188, 232, 255), (255, 255, 255), ( 12,  28,  44)),
    "lightning": ((232, 196,  48), (255, 246, 168), (255, 255, 255), ( 38,  32,   8)),
    "thunder":   ((150, 150, 190), (214, 216, 244), (255, 255, 255), ( 24,  24,  38)),
    "radiant":   ((236, 194,  86), (255, 238, 176), (255, 255, 255), ( 44,  34,  10)),
    "necrotic":  ((112, 156,  86), (170, 206, 126), (214, 240, 178), ( 18,  26,  14)),
    "poison":    (( 96, 180,  76), (160, 228, 116), (222, 252, 186), ( 14,  30,  12)),
    "force":     ((168, 104, 216), (214, 168, 248), (246, 226, 255), ( 28,  14,  40)),
    "heal":      (( 92, 190, 140), (168, 236, 196), (246, 255, 246), ( 12,  34,  24)),
    # schools, for spells with neither damage nor healing
    "abjuration":    ((104, 148, 200), (172, 208, 248), (240, 248, 255), ( 14,  24,  40)),
    "conjuration":   (( 72, 186, 182), (150, 232, 228), (234, 255, 254), ( 10,  32,  32)),
    "enchantment":   ((206, 108, 168), (246, 168, 210), (255, 232, 244), ( 38,  14,  28)),
    "transmutation": ((208, 148,  60), (248, 204, 122), (255, 240, 200), ( 40,  28,   8)),
    "evocation":     ((200, 110,  70), (244, 176, 128), (255, 232, 206), ( 36,  18,  12)),
    "illusion":      ((140, 128, 214), (196, 190, 248), (240, 238, 255), ( 22,  20,  40)),
    "divination":    ((122, 178, 206), (186, 226, 244), (244, 252, 255), ( 18,  30,  38)),
    "necromancy":    ((112, 156,  86), (170, 206, 126), (214, 240, 178), ( 18,  26,  14)),
    # the two non-spell actions
    "steel":     ((158, 166, 178), (216, 222, 232), (255, 255, 255), ( 22,  24,  28)),
    "bronze":    ((186, 134,  70), (236, 196, 132), (255, 238, 206), ( 34,  24,  12)),
}

# -- Glyphs -----------------------------------------------------------------
# '.' transparent  '#' main  '+' light  '*' accent  'o' shadow (main x0.45)
# Rows are right-padded to CELL, so only the drawn part has to be written out.
GLYPH = {}

GLYPH["swords"] = """
..++........++..
..+o+......+o+..
...+o+....+o+...
....+o+..+o+....
.....+o++o+.....
......+oo+......
......o++o......
.....+o..o+.....
....+o....o+....
...*o......o*...
..***......***..
...*#......#*...
...*#......#*...
....*......*....
"""

GLYPH["hourglass"] = """
..############..
...#........#...
...#.++++++.#...
....#.++++.#....
.....#.++.#.....
......#..#......
......#++#......
......#**#......
......#..#......
.....#.**.#.....
....#.****.#....
...#.******.#...
...#........#...
..############..
"""

GLYPH["bolt_diag"] = """
..............+.
............++*.
...........+**#.
..........+**##.
.........+**##..
........+**##...
.......***##....
......***##.....
.....***##......
....***##.......
...***##........
..**##..........
..*##...........
.*##............
.##.............
"""

GLYPH["cone"] = """
..#.............
..##............
..#*#...........
..#**#..........
..#***#.........
..#*++*#........
..#*+++*#.......
..#*++++*#......
..#*+++++*#.....
..#*++++++*#....
..#*+++++++*#...
..#*++++++++*#..
..#**********#..
..############..
"""

GLYPH["burst"] = """
.......*........
..*....*....*...
...*...*...*....
....*..*..*.....
.....##+##......
....#+***+#.....
.*..#+***+#..*..
****#**+**#*****
.*..#+***+#..*..
....#+***+#.....
.....##+##......
....*..*..*.....
...*...*...*....
..*....*....*...
"""

GLYPH["rays3"] = """
...........+**#.
.........+**#...
.......+**#.....
.....+**#.......
...+**#.........
................
...........+**#.
.........+**#...
.......+**#.....
.....+**#.......
................
...........+**#.
.........+**#...
.......+**#.....
"""

GLYPH["forked_beam"] = """
.............**.
............**+.
...........**+..
.........***+...
........**+.....
.....*****......
...***+.........
.*****..........
...***..........
.....*****......
........**+.....
.........***+...
...........**+..
............**+.
"""

GLYPH["darts3"] = """
..**............
..***+++++++....
..**............
................
....**..........
....***+++++++..
....**..........
................
.**.............
.***+++++++.....
.**.............
"""

GLYPH["mace"] = """
.....*..*..*....
....*##++##*....
....##+**+##....
...*#+****+#*...
...*#******#*...
....##****##....
....*##++##*....
.....*.##.*.....
.......##.......
.......##.......
.......##.......
.......##.......
......####......
......#++#......
"""

GLYPH["shield"] = """
...##########...
..#++++++++++#..
..#+#######+#+..
..#+#*****#+#+..
..#+#*+++*#+#+..
..#+#*+#+*#+#+..
..#+#*+++*#+#+..
...#+#***#+#+...
...#++###++#+...
....#++++++#....
.....#++++#.....
......#++#......
.......##.......
"""

GLYPH["icicle"] = """
...+#...........
...+#...........
..+##...........
..+#*#..........
..+#**#.........
...+#**#........
....+#**#.......
.....+#**#......
......+#**#.....
.......+#**#....
........+#**#...
.........+#*#...
..........+##...
...........+....
"""

GLYPH["hand_spark"] = """
..........+#....
.........+#.....
........+#......
.......+####....
......+#+#......
.....+#.........
....#.#.#.......
...#+#+#+#......
...#+#+#+#......
..#+++++++#.....
..#+++++++#.....
...#+++++#......
....#####.......
"""

GLYPH["zigzag"] = """
..........++#...
.........++#....
........++#.....
.......++#......
......++#.......
.....+++####....
....++#+++++....
.......++#......
......++#.......
.....++#........
....++#.........
...++#..........
..++#...........
..+#............
"""

GLYPH["arcs"] = """
......*.........
.....**.........
....**..........
...**...*.......
..**...**..*....
.**...**..**....
.#*...*#..*#....
.#*...*#..*#....
.**...**..**....
..**...**..*....
...**...*.......
....**..........
.....**.........
......*.........
"""

GLYPH["crack"] = """
.....#..........
....#+#....#....
...#+++#..#+#...
...#+++#.#+++#..
....#+#..#+++#..
.....#....#+#...
................
..#........#....
.#+#......#+#...
#+++#....#+++#..
.#+++#..#+++#...
..#+#....#+#....
...#......#.....
"""

GLYPH["flame_halo"] = """
....*******.....
...*.......*....
.......#........
......#+#.......
.....##+##......
.....#+++#......
....##+*+##.....
....#++*++#.....
...##+***+##....
...#++***++#....
...#++***++#....
....##+*+##.....
.....#####......
"""

GLYPH["star_beam"] = """
......*.........
...*..*..*......
....*.*.*.......
..*****#*****...
....*#+#*.......
...*#+++#*......
..*..#+#..*.....
.......#+.......
........+#......
.........+#.....
..........+#....
...........+#...
............+#..
.............+#.
"""

GLYPH["cross"] = """
......####......
......#++#......
......#++#......
..#####++#####..
..#++++++++++#..
..#+++****+++#..
..#+++****+++#..
..#++++++++++#..
..#####++#####..
......#++#......
......#++#......
......####......
"""

GLYPH["cross_arcs"] = """
......####......
......#++#......
......#++#......
.*.####++####.*.
.*.#++++++++#.*.
.*.#+++**+++#.*.
.*.#+++**+++#.*.
.*.#++++++++#.*.
.*.####++####.*.
......#++#......
......#++#......
......####......
"""

GLYPH["cross_sparks"] = """
.*...........*..
......####......
......#++#......
...####++####...
...#++++++++#...
...#+++**+++#...
...#+++**+++#...
...#++++++++#...
...####++####...
......#++#......
......####......
.*...........*..
"""

GLYPH["bell"] = """
.......##.......
......#++#......
......#++#......
.....#++++#.....
....#++++++#....
....#++++++#....
...#++++++++#...
...#++++++++#...
...#++++++++#...
..############..
.##############.
......####......
......#**#......
"""

GLYPH["skeletal_hand"] = """
....#.#.#.......
...#+#+#+#......
...#+#+#+#......
...#+#+#+#..#...
...#+++++#.#+#..
..#+++++++#+#...
..#+++++++++#...
..#+++++++++#...
...#+++++++#....
....#+++++#.....
.....#####......
......#.#.......
"""

GLYPH["skull"] = """
....########....
...#++++++++#...
..#++++++++++#..
..#+##++##+++#..
..#+#oo##oo#++#.
..#+#oo##oo#++#.
..#++++##++++#..
..#+++####+++#..
...#++++++++#...
....#+#++#+#....
....########....
.....#.##.#.....
.....######.....
"""

GLYPH["rune_eye"] = """
....########....
..##++++++++##..
.#++++####++++#.
#+++##****##+++#
#+++#**oo**#+++#
#+++##****##+++#
.#++++####++++#.
..##++++++++##..
....########....
"""

GLYPH["zzz"] = """
......#######...
...........##...
.........##.....
.......##.......
......#######...
................
..#####.........
......##........
....##..........
..#####.........
"""

GLYPH["figure_bound"] = """
......####......
......#++#......
......####......
.....######.....
...##########...
....#++++++#....
....#++++++#....
...##########...
.....#+..+#.....
.....#+..+#.....
....##....##....
....##....##....
"""

GLYPH["droplets"] = """
...........###..
..........#+++#.
..........#+*+#.
...........###..
......###.......
.....#+++#......
.....#+*+#......
......###.......
.###............
#+++#...........
#+*+#...........
.###............
"""

GLYPH["boot_mist"] = """
..**...**...**..
.*..*.*..*.*..*.
..**...**...**..
.....####.......
.....#++#.......
.....#++#.......
.....#++#.......
.....#++####....
.....#++++++#...
.....#++++++#...
.....########...
....**........**
..**....**....**
"""

GLYPH["no_circle"] = """
.....######.....
...##++++++##...
..#++#...*#++#..
..#+#...*..#+#..
.#+#...*....#+#.
.#+#..*.....#+#.
.#+#.*......#+#.
..#+#*.....#+#..
..#++#....#++#..
...##++++++##...
.....######.....
"""

GLYPH["wing"] = """
.#..............
.##.............
.#+#............
.#++##..........
.#++++##........
.#++++++##......
.#+*+*+*++##....
.#+*+*+*+*+##...
.#+*+*+*+*+*+#..
.#+*+*+*+*+*+#..
.#++*+*+*+*++#..
..#+++++++++#...
...##########...
"""

# spell id -> glyph name. Anything missing falls back to its school's glyph.
SPELL_GLYPH = {
    "fire_bolt": "bolt_diag",       "burning_hands": "cone",         "fireball": "burst",
    "scorching_ray": "rays3",       "eldritch_blast": "forked_beam", "magic_missile": "darts3",
    "spiritual_weapon": "mace",     "shield": "shield",              "ray_of_frost": "icicle",
    "shocking_grasp": "hand_spark", "lightning_bolt": "zigzag",      "thunderwave": "arcs",
    "shatter": "crack",             "sacred_flame": "flame_halo",    "guiding_bolt": "star_beam",
    "cure_wounds": "cross",         "prayer_of_healing": "cross_arcs",
    "mass_healing_word": "cross_sparks", "toll_the_dead": "bell",
    "chill_touch": "skeletal_hand", "animate_dead": "skull",         "hex": "rune_eye",
    "sleep": "zzz",                 "hold_person": "figure_bound",   "poison_spray": "droplets",
    "misty_step": "boot_mist",      "counterspell": "no_circle",     "fly": "wing",
}

SCHOOL_GLYPH = {
    "abjuration": "shield",    "conjuration": "burst",     "divination": "rune_eye",
    "enchantment": "zzz",      "evocation": "burst",       "illusion": "rune_eye",
    "necromancy": "skull",     "transmutation": "wing",
}

# The action-bar rows that are not spells.
EXTRA = {"attack": ("swords", "steel"), "end_turn": ("hourglass", "bronze")}


def parse_glyph(art):
    rows = [r for r in art.strip("\n").split("\n")]
    out = []
    for r in rows:
        if len(r) > CELL:
            raise ValueError("glyph row is %d wide, max %d: %r" % (len(r), CELL, r))
        out.append(r.ljust(CELL, "."))
    if len(out) > CELL:
        raise ValueError("glyph is %d rows, max %d" % (len(out), CELL))
    # centre vertically so a short glyph is not top-heavy in the slot
    pad = (CELL - len(out)) // 2
    return ["." * CELL] * pad + out + ["." * CELL] * (CELL - len(out) - pad)


def render_icon(glyph_name, palette):
    main, light, accent, badge = PAL[palette]
    shadow = tuple(int(c * 0.45) for c in main)
    colors = {"#": main, "+": light, "*": accent, "o": shadow}

    img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    px = img.load()
    # Badge plate: a rounded square, so the icon reads as a slot rather than a floating shape.
    for y in range(CELL):
        for x in range(CELL):
            corner = (x in (0, CELL - 1)) and (y in (0, CELL - 1))
            if not corner:
                px[x, y] = badge + (232,)
    # A one-pixel rim in the palette's main colour keys the slot to the spell.
    rim = tuple(int(c * 0.75) for c in main) + (255,)
    for i in range(1, CELL - 1):
        px[i, 0] = rim
        px[i, CELL - 1] = rim
        px[0, i] = rim
        px[CELL - 1, i] = rim

    for y, row in enumerate(parse_glyph(GLYPH[glyph_name])):
        for x, ch in enumerate(row):
            if ch in colors:
                px[x, y] = colors[ch] + (255,)
    return img.resize((SIZE, SIZE), Image.NEAREST)


def load_spells():
    spells = []
    for f in sorted(glob.glob(os.path.join(SPELL_DIR, "*.json"))):
        d = json.load(open(f, encoding="utf-8"))
        spells.extend(d if isinstance(d, list) else d.get("spells", []))
    return spells


def palette_for(spell):
    dmg = (spell.get("damageType") or "").lower()
    if dmg in PAL:
        return dmg
    if spell.get("healDice") or spell.get("healBase"):
        return "heal"
    return (spell.get("school") or "evocation").lower()


def glyph_for(spell):
    sid = spell["id"]
    if sid in SPELL_GLYPH:
        return SPELL_GLYPH[sid]
    return SCHOOL_GLYPH.get((spell.get("school") or "").lower(), "burst")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet", action="store_true", help="also write a contact sheet")
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if any spell's icon file is missing")
    args = ap.parse_args()

    spells = load_spells()
    if not spells:
        print("no spells found under %s" % SPELL_DIR, file=sys.stderr)
        return 1

    if args.check:
        no_glyph = [s["id"] for s in spells if s["id"] not in SPELL_GLYPH]
        absent = [s["id"] for s in spells
                  if not os.path.exists(os.path.join(OUT_DIR, s["id"] + ".png"))]
        absent += [n for n in EXTRA if not os.path.exists(os.path.join(OUT_DIR, n + ".png"))]
        for sid in no_glyph:
            print("note: spell '%s' has no glyph of its own (uses its school's)" % sid)
        for sid in absent:
            print("MISSING ICON FILE: %s.png - run tools/gen_spell_icons.py" % sid)
        print("%d spells, %d with their own glyph, %d icon files missing"
              % (len(spells), len(spells) - len(no_glyph), len(absent)))
        return 1 if absent else 0

    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for s in spells:
        render_icon(glyph_for(s), palette_for(s)).save(os.path.join(OUT_DIR, s["id"] + ".png"))
        written.append((s["id"], s["name"], glyph_for(s), palette_for(s)))
    for name, (g, p) in EXTRA.items():
        render_icon(g, p).save(os.path.join(OUT_DIR, name + ".png"))
        written.append((name, name, g, p))
    # Per-school fallbacks, so a spell added to the JSON still gets a sensible icon
    # even before this script is re-run.
    for school, g in SCHOOL_GLYPH.items():
        render_icon(g, school).save(os.path.join(OUT_DIR, "school_" + school + ".png"))

    for sid, nm, g, p in written:
        print("  %-20s %-22s %-14s %s" % (sid, nm, g, p))
    print("%d icons -> %s" % (len(written) + len(SCHOOL_GLYPH), OUT_DIR))

    if args.sheet:
        cols = 8
        rows = (len(written) + cols - 1) // cols
        pad, label_h = 8, 14
        sheet = Image.new("RGB", (cols * (SIZE + pad) + pad,
                                  rows * (SIZE + pad + label_h) + pad), (24, 24, 28))
        d = ImageDraw.Draw(sheet)
        for i, (sid, nm, g, p) in enumerate(written):
            cx = pad + (i % cols) * (SIZE + pad)
            cy = pad + (i // cols) * (SIZE + pad + label_h)
            ic = Image.open(os.path.join(OUT_DIR, sid + ".png"))
            sheet.paste(ic, (cx, cy), ic)
            d.text((cx, cy + SIZE + 2), sid[:16], fill=(200, 200, 210))
        out = os.path.join(REPO, "docs", "evidence", "ravenmere", "spell_icon_sheet.png")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        sheet.save(out)
        print("contact sheet -> %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
