#!/usr/bin/env python3
"""Regenerate shaders/grass_shadow.vert from shaders/grass.vert.

RUN THIS AFTER EVERY EDIT TO grass.vert. The two shaders must agree on blade placement, wind and
density-LOD math exactly; if they drift, a blade's shadow detaches from the blade casting it.

The sibling differs in exactly TWO substitutions:

  1. `kShadowWidthGate` 0.0 -> 1.0. One constant gates every shadow-only behaviour in grass.vert,
     so the visible pass is provably untouched by them:
       * the blade turns BROADSIDE to the sun (a blade whose hashed yaw points along the light
         projects zero width and casts nothing at all);
       * blade width is multiplied by pc.shadowWidthScale (default 2.0) so the shadow is slightly
         wider than its caster.
  2. `ubo.viewProj` -> `ubo.lightSpaceMatrix` in the gl_Position line.

Everything else is copied byte-for-byte. If you need a third difference, add it as another
gate-guarded branch in grass.vert rather than as a substitution here — a substitution is invisible
to anyone reading grass.vert, and this file has already drifted once (its banner described a
`kMinShadowTexels` clamp for weeks after that clamp was removed).

Guarded by tests/graphics/GrassShaderMirrorTest.cpp, which asserts the on-disk diff is exactly the
banner plus these two lines.

NOTE: build_shaders.bat does not track #include dependencies, so after regenerating you must
recompile BOTH grass shaders (running build_shaders.bat does this).
"""
import io
import sys

SRC = 'G:/Github/phyxel/shaders/grass.vert'
DST = 'G:/Github/phyxel/shaders/grass_shadow.vert'

BANNER = '''
// ===========================================================================================
// GENERATED SIBLING of grass.vert - GRASS SHADOW CASTER.
// DO NOT EDIT BY HAND. Regenerate with tools/regen_grass_shadow.py whenever grass.vert changes.
// Differs from grass.vert in exactly TWO ways:
//   1. kShadowWidthGate 1.0 instead of 0.0 -> the blade turns broadside to the sun and its width
//      is multiplied by pc.shadowWidthScale (a blade edge-on to the light would cast nothing).
//   2. projects with ubo.lightSpaceMatrix instead of ubo.viewProj.
// Blade placement, wind and density-LOD math MUST stay identical or a blade's shadow detaches
// from the blade casting it (same contract as foliage.vert <-> foliage_shadow.vert).
// ===========================================================================================
'''

SUBS = [
    ('gl_Position = ubo.viewProj * vec4(worldPos, 1.0);',
     'gl_Position = ubo.lightSpaceMatrix * vec4(worldPos, 1.0);',
     'projection line'),
    ('const float kShadowWidthGate = 0.0;',
     'const float kShadowWidthGate = 1.0;   // SHADOW PASS: face the sun + widen the proxy',
     'shadow gate'),
]


def main():
    src = io.open(SRC, encoding='utf-8').read()

    for old, new, what in SUBS:
        n = src.count(old)
        if n != 1:
            sys.exit(f"ERROR: expected exactly 1 '{what}' in grass.vert, found {n}. "
                     f"Refusing to generate a shader that may differ in more than the two "
                     f"sanctioned ways.")
        src = src.replace(old, new, 1)

    if src.count('#version 450') != 1:
        sys.exit("ERROR: expected exactly one '#version 450' in grass.vert")
    # rstrip the banner's trailing newline: grass.vert already supplies the newline before its
    # next line, and a stray blank here makes the generated file differ from grass.vert by a line
    # the mirror test cannot attribute to either sanctioned substitution.
    src = src.replace('#version 450', '#version 450' + BANNER.rstrip('\n'), 1)

    io.open(DST, 'w', encoding='utf-8').write(src)
    print('grass_shadow.vert regenerated from grass.vert (gate=1.0, light-space projection)')
    print('NOW RUN build_shaders.bat — SPIR-V is not regenerated by this script.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
