#!/usr/bin/env python3
"""Detect SPIR-V binaries that are stale with respect to their GLSL sources.

WHY THIS EXISTS
---------------
shaders/*.spv are COMMITTED build artifacts, and glslc/glslangValidator do NOT track `#include`
dependencies. That combination shipped a real bug: the transposed-AgX fix (20341333) edited
shaders/lighting.glsl -- the shared lighting model #included by eleven shaders -- and committed the
source alone. Every other checkout kept five-day-old .spv with the broken matrices and rendered a
pink world, while the machine that made the fix looked correct because its .spv were rebuilt locally
and never committed.

Nothing detected that. This does.

WHY HASHES AND NOT A BYTE COMPARE
---------------------------------
Recompiling and byte-comparing the .spv would flag every developer whose Vulkan SDK version differs
from whoever last built, because SPIR-V output is not stable across compiler versions. What we
actually care about is narrower and version-independent: "was this .spv built from the sources as
they exist now?" So we hash each shader's source plus its full transitive include set, record that
in shaders/shader_manifest.json at compile time, and compare hashes on check.

USAGE
    python tools/shader_manifest.py --update   # after a successful shader build
    python tools/shader_manifest.py --check    # exits 1 and lists stale shaders

`--update` is invoked automatically at the end of build_shaders.bat, so the normal workflow keeps
the manifest honest without anyone remembering to.
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SHADER_DIR = REPO / "shaders"
MANIFEST = SHADER_DIR / "shader_manifest.json"

INCLUDE_RE = re.compile(r'^\s*#include\s+"([^"]+)"', re.MULTILINE)
STAGE_SUFFIXES = (".vert", ".frag", ".comp", ".geom", ".tesc", ".tese")


def transitive_sources(path: Path, seen=None):
    """Return the shader plus every file it #includes, transitively.

    Missing includes are skipped rather than raised: a shader that does not compile is the compiler's
    problem to report, not this script's.
    """
    if seen is None:
        seen = []
    path = path.resolve()
    if path in seen or not path.exists():
        return seen
    seen.append(path)
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return seen
    for inc in INCLUDE_RE.findall(text):
        transitive_sources((path.parent / inc), seen)
    return seen


def source_hash(shader: Path) -> str:
    """Hash the shader and its include set. Include PATHS are hashed alongside contents so that
    adding or removing an include changes the result even if the bytes happen to coincide."""
    h = hashlib.sha256()
    for src in sorted(transitive_sources(shader), key=lambda p: str(p).lower()):
        h.update(str(src.relative_to(REPO)).replace("\\", "/").encode())
        h.update(b"\0")
        h.update(src.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


BUILD_SCRIPT = REPO / "build_shaders.bat"


def built_shader_names():
    """Shader files build_shaders.bat actually compiles.

    Scoping to these matters: shaders/ also holds orphans that nothing builds and nothing
    references (solver_apply.comp has been dead since May). Failing the check on those would train
    people to ignore it, which is worse than not having it.
    """
    if not BUILD_SCRIPT.exists():
        return None
    text = BUILD_SCRIPT.read_text(encoding="utf-8", errors="replace")
    stages = "|".join(s.lstrip(".") for s in STAGE_SUFFIXES)
    return set(re.findall(r"shaders[\\/]([A-Za-z0-9_]+\.(?:" + stages + r"))\b", text))


def shader_sources():
    for p in sorted(SHADER_DIR.iterdir()):
        if p.suffix in STAGE_SUFFIXES and p.is_file():
            yield p


def build_map():
    built = built_shader_names()
    out = {}
    for shader in shader_sources():
        spv = shader.with_suffix(shader.suffix + ".spv")
        out[shader.name] = {
            "sources": source_hash(shader),
            "spv_present": spv.exists(),
            "built": (built is None) or (shader.name in built),
        }
    return out


def cmd_update():
    data = {
        "_comment": "Auto-generated by tools/shader_manifest.py --update; refreshed by "
                    "build_shaders.bat. Records the hash of each shader plus its transitive "
                    "#includes at the time its .spv was built.",
        "shaders": build_map(),
    }
    MANIFEST.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("shader_manifest: recorded {} shaders".format(len(data["shaders"])))
    return 0


def cmd_check():
    if not MANIFEST.exists():
        print("shader_manifest: MISSING {}".format(MANIFEST.relative_to(REPO)))
        print("  run: python tools/shader_manifest.py --update  (after building shaders)")
        return 1

    recorded = json.loads(MANIFEST.read_text(encoding="utf-8")).get("shaders", {})
    current = build_map()

    stale, missing_spv, untracked, orphans = [], [], [], []
    for name, info in sorted(current.items()):
        if not info.get("built", True):
            # Source present but no build rule -- dead file, or someone forgot build_shaders.bat.
            # Reported, never fatal.
            if not info["spv_present"]:
                orphans.append(name)
            continue
        if not info["spv_present"]:
            missing_spv.append(name)
            continue
        if name not in recorded:
            untracked.append(name)
        elif recorded[name]["sources"] != info["sources"]:
            stale.append(name)

    built_count = sum(1 for i in current.values() if i.get("built", True))
    if not (stale or missing_spv or untracked):
        print("shader_manifest: OK -- {} built shaders, all .spv current with their sources".format(built_count))
        for n in orphans:
            print("  note: {} has no build rule and no .spv (orphaned source)".format(n))
        return 0

    print("shader_manifest: STALE SPIR-V DETECTED")
    if stale:
        print("\n  These .spv were built from OLDER sources than are checked in.")
        print("  A shared include (e.g. lighting.glsl) very likely changed:")
        for n in stale:
            print("      {}.spv".format(n))
    if missing_spv:
        print("\n  These shaders have NO compiled .spv at all:")
        for n in missing_spv:
            print("      {}".format(n))
    if untracked:
        print("\n  These shaders are not in the manifest (new, or manifest never updated):")
        for n in untracked:
            print("      {}".format(n))
    print("\n  Fix: run build_shaders.bat, then COMMIT the regenerated .spv along with your")
    print("  source change. .spv are committed artifacts -- shipping the .glsl alone means every")
    print("  other checkout keeps rendering the old shader.")
    return 1


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--update", action="store_true", help="record current source hashes")
    g.add_argument("--check", action="store_true", help="fail if any .spv is stale")
    args = ap.parse_args()
    return cmd_update() if args.update else cmd_check()


if __name__ == "__main__":
    sys.exit(main())
