function(enable_sanitizers project_name)
    if(MSVC)
        # MSVC Address Sanitizer (requires Visual Studio 2019 16.9+)
        option(ENABLE_ASAN "Enable Address Sanitizer" OFF)
        if(ENABLE_ASAN)
            target_compile_options(${project_name} PRIVATE /fsanitize=address)
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        option(ENABLE_ASAN "Enable Address Sanitizer" OFF)
        if(ENABLE_ASAN)
            target_compile_options(${project_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${project_name} PRIVATE -fsanitize=address)
        endif()
        
        option(ENABLE_TSAN "Enable Thread Sanitizer" OFF)
        if(ENABLE_TSAN)
            target_compile_options(${project_name} PRIVATE -fsanitize=thread)
            target_link_options(${project_name} PRIVATE -fsanitize=thread)
        endif()
    endif()
endfunction()
